hyperledger-labs/fabric-operations-console

- packages/athena/json_docs/default_settings_doc.json
fixes error:
```
08:57:09 - error: [db startup] unable to read json file. cannot add to database. ../json_docs/template.json message=Cannot find module '../json_docs/template.json'
```
> remote template.json line in default settings file

- packages/athena/libs/component_lib.js
The max component limit is counting signature collection docs, which wasn't intended. The max component limit should only limit the number of peers/cas/orderers based on the number of peers/cas/orderers.
> fix max component limit, only count peers/cas/os

- FAQ.md
- packages/athena/env/README.md
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/libs/authentication_lib.js
- packages/athena/libs/middleware/middleware.js
- packages/athena/libs/settings.js
added the setting `allow_default_password`
- if `true` users are allowed to keep the default password
- if `false` users will be forced to set a new password after their first login
- defaults `false`
https://github.com/hyperledger-labs/fabric-operations-console/issues/79
> create setting to allow users to keep default pass

- packages/athena/libs/deployer_lib.js
- packages/athena/libs/patch_lib.js
- packages/athena/routes/other_apis.js
The auto fabric upgrade logic was not parsing the get-available-fabric-versions api response correctly, causes the upgrade api to fail.
This PR also now ignores the db setting `DISABLE_AUTO_FAB_UP` when calling the fabric upgrade manually. meaning the setting `DISABLE_AUTO_FAB_UP` only applies to the automatic fabric upgrade logic.
> Fix auto fabric upgrade parsing

- packages/athena/docs/db_backup_apis.md
- packages/athena/libs/db_backup.js
This adds a skip doc query parameter to the restore api. This will allow use of the restore api w/o having to modify the backup object in order to NOT restore certain documents.
This PR also rebuilds the component whitelist once a restore is complete.  This should allow the console to operate with the components found in its db.
query params:
```js
skip_system="['00_settings_athena']"	// [optional] docs that match these ids will not be restored to the system db
skip_component="['abcd']"	// [optional] docs that match these ids will not be restored to the components db
```
> add skip param to restore api + rebuild white list

- packages/athena/json_docs/default_settings_doc.json
- packages/athena/libs/misc.js
- packages/athena/libs/patch_lib.js
- packages/athena/test/test-suites/lib/misc.test.js
- Bug fix
- the auto upgrade fabric logic was upgrading from versions that were okay. it was upgrading all orderers to the highest available major fabric version, unless they were already at the highest level (within the same major version).
> Auto upgrade version fix

- packages/athena/libs/misc.js
- packages/athena/test/test-suites/lib/misc.test.js
- Bug fix
The version comparison logic did not work correctly when comparing 1 double digit version to a single digit version.
> fix version compare logic with double digit str

- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- Bug fix
The "refresh cert" button should show up for deployed nodes and not show for imported nodes. This was not working as intended for orderering nodes. If the first orderer in an OS (when sorted by name alphabetically) was a deployed node, the console would show the button on all ordering nodes in that OS.
> fix refresh cert button, only show for deploy node

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/components/PeerModal/PeerModal.js
- packages/apollo/src/utils/helper.js
- packages/athena/docs/_holy_cert.md
- packages/athena/libs/comp_formatting_lib.js
- packages/athena/libs/component_lib.js
- Bug fix
This pr allows identities from an intermediate CA to be available in the associate drop down.
https://github.com/hyperledger-labs/fabric-operations-console/issues/109
> allow associating identities from intermediate ca

- packages/apollo/.secrets.baseline
- packages/apollo/src/components/IdentityExpiration/IdentityExpiration.js
- packages/athena/.secrets.baseline
- packages/stitch/.secrets.baseline
- Bug fix
The associated identity box is still showing the 'non-admin identity' warning when configured with Node OU, but don't have the admin cert in the MSP
> fix false positive - admin identity

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- Improvement 
Improves the error message if you try to remove an OS with no identity associated with the OS nodes.
> improve error on remove if OS has no identity

- packages/apollo/src/components/Identities/Identities.js
- Bug fix
Recreation:
Create a CA
Create Identities in Wallet
Export CA
Import CA (so that you have a copy)
Visit the Wallet page - the page goes blank
> fix disappearing wallet

- packages/apollo/src/components/OrdererDetails/ChannelParticipationDetails.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- New feature
Display channel info specific to the ordering service node when drilling down
> add channel info on osn drill down

- packages/athena/app.js
- Bug fix
The added body parser is breaking the configtxlator proxy route. This moves that parser from the global scope to just the generic proxy route.
> apply multipart bodyParser to the proxy route only

- packages/athena/public/releaseNotes.json
- packages/stitch/src/libs/proto_handlers/collection_pb_lib.ts
- packages/stitch/src/libs/proto_handlers/lifecycle_pb_lib.ts
- packages/stitch/src/libs/proto_handlers/policy_pb_lib.ts
- packages/stitch/src/stitch.ts
- packages/stitch/test/stitch.test.js
- Bug fix
- fix MSP Role formatting in a chaincode definition, was always being set to `MEMBER`
- remove an empty `endorsementPolicy` if a endorsment policy was not set in a Static Collection Config
> Stitch policy fixes

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/ChangePasswordModal/ChangePasswordModal.js
- packages/apollo/src/components/Login/Login.js
- packages/apollo/src/components/Members/Members.js
- packages/apollo/src/components/ReleaseNotes/ReleaseNotes.js
- packages/apollo/src/components/ReleaseNotes/_releaseNotes.scss
- packages/apollo/test/unit/tests/Login.test.jsx
- packages/athena/public/releaseNotes.json
- Bug fix
- The reset password modal was allowing a user to click submit even if there were password strength errors.  The password was still being rejected, but disabling the submit button is the desired behavior.
- Adds release notes
> Tweak pass submit button

- packages/athena/json_docs/json_validation/ibp_openapi_v2.yaml
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/libs/validation_lib.js
- Improvement (safety)
- will reject apis to create a peer or orderer using an unknown CA hostname. 
- failures generate: `The parameter 'crypto.enrollment.ca.host' was not found in the list of known hostnames. Import the CA using this hostname or use a hostname that is already known.`
> validate CA enrollment host during create peer/os

- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/Channels/Channels.js
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/libs/signature_collection_lib.js
- Bug fix
- Fixed an issue with a missing msp id that fails to build a proper signature authorize field. Happens during channel creation.
- Adds some server side logs to help identify the missing msp id issue
- Adds case sensitive flag to fabric gateway config-override validation (unrelated to channel issue)
- Fixed issue where the application/orderer/channel capabilities were being set on a create-channel flow causing create failures.
> Fix signature auth - channel creation

- packages/athena/libs/deployer_lib.js
- Bug fix
The cached deployer data cannot be used to synchronize the state of the component. It should be skipped, unless the real (up-to-date) data was obtained.
> do not run k8s sync w/cached deployer data

- packages/apollo/src/components/MSPDefinitionModal/MSPDefinitionModal.js
Historically Fabric required admin certs for an organization... somewhere around 1.4 when Node OU was introduced, admin certs in the orgs were no longer required. Adjusting the code to accommodate that
https://github.com/hyperledger-labs/fabric-operations-console/issues/203
> allow zero length admin array for org

- packages/athena/libs/component_lib.js
- packages/athena/libs/misc.js
- packages/athena/libs/ot_misc.js
- packages/athena/libs/validation_lib.js
- packages/athena/routes/deployer_apis.js
- packages/athena/test/test-suites/lib/misc.test.js
- packages/athena/test/test-suites/routes/deployer_apis.test.js
- Bug fix
When creating a component the hostname safelist will be recalculated before API validation. 
This will fix the problem when a user creates a peer and the hostname of the CA for the peer's enrollment is not known to all instances of the console.
> rebuild safelist when validating create-peer api

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/ChannelConsenterModal/ChannelConsenterModal.js
- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
- packages/apollo/src/components/ChannelModal/ChannelModal.js
- Bug fix
- cannot remove consenter from channel details page, msp drop down is empty.
- from the channel details page the MSP data was only being retrieved if `isTLSCertMismatchFound` was true. This PR removes that condition and will always populate the MSP data. This data is required for the removed-consenter flow.
- also fixes the description text on the remove-consenter flow
> always get all msps on channel details page

- packages/stitch/src/libs/misc.ts
- packages/stitch/src/libs/proto_handlers/block_pb_lib.ts
- packages/stitch/src/stitch.ts
- packages/stitch/test/stitch.test.js
- Improvement 
Add support for decoding utf8 characters in fabric transaction outputs.  Specifically the read/write set from a transaction will now display correctly * **if** * utf8 characters were used.
fixes https://github.com/hyperledger-labs/fabric-operations-console/issues/198
> add support for stitch to decode utf8 characters

- packages/stitch/src/libs/proto_handlers/block_pb_lib.ts
- packages/stitch/src/libs/proto_handlers/lifecycle_pb_lib.ts
- Improvement 
Add support for decoding utf8 characters in fabric transaction  * inputs *.  Similar to https://github.com/hyperledger-labs/fabric-operations-console/pull/210
fixes https://github.com/hyperledger-labs/fabric-operations-console/issues/198
> add support for stitch to decode utf8 characters - input

- packages/athena/libs/middleware/middleware.js
For automation purposes it would be nice if the console settings can be edited using the default password. This PR does that.
> allow edit-settings api to use default password

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/ImportOrdererModal/ImportOrdererModal.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/libs/comp_formatting_lib.js
- New feature
- Added ability to create orderers w/o a system channel. it is selectable via a checkbox. requires deployer to be present and the feature flag `osnadmin_feats_enabled` to be true.
- note if this is selected channel participation APIs must be used to create application channels
> add option to create system channel-less orderers

- packages/apollo/.secrets.baseline
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/athena/.secrets.baseline
- packages/stitch/.secrets.baseline
- Bug fix
Currently when deleting an ordering node without system channel, we still check for system channel to remove the node from consenters. This step needs to be skipped when dealing with nodes that don't have system channel.
> remove system channel check with deleting node without system channel

- packages/apollo/src/components/OrdererDetails/ChannelParticipationUnjoinModal.js
- Bug fix
Suppress 404/503 - the check for maintenance mode goes across all nodes in the cluster and some nodes may not have system channel (since they have been removed)
> Suppress 404/503

- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/ImportOrdererModal/ImportOrdererModal.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/NodeRestApi.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/athena/libs/deployer_lib.js
- New feature
- Added the ability to append ordering nodes to an existing cluster that are * not * using a system channel.
- This also introduces some performance improvements by eliminating some redundant apis/spam
> add ability to append ordering node to systemless

- packages/apollo/src/components/MSPDefinitionModal/MSPDefinitionModal.js
- Bug fix
Fixes an error when importing a MSP json file with no `intermediate_certs` field. This field can be blank or missing and the import should still succeed.
> fix msp import if there are no intermediate_certs

- packages/apollo/src/components/ChannelModal/_channelModal.scss
- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- Bug fix
- chooses the correct identity for the join osn flow, uses the same logic as the get-config-block code
- removes the drop down to select an identity for the join osn flow
> remove the identity drop down in the join flow

- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/utils/helper.js
- packages/athena/libs/comp_formatting_lib.js
- packages/athena/libs/component_lib.js
- packages/athena/libs/validation_lib.js
- packages/stitch/src/libs/fabric_rest.ts
- Bug fix
- fixes the response to get-osn-channels when there are 0 channels. makes it an empty array instead of null.
- fixes `system_channel_id` filed being set to null, should be empty string when there is no system channel
> fix get-channels logic if response is empty

- packages/apollo/src/components/OrdererDetails/ChannelParticipationDetails.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/rest/ChannelParticipationApi.js
- Bug fix
- the unjoin button from the system channel was not being shown, it now shows
- the ignore delete warnings was not be shown on orderers that used a system channel, it now shows on all orderers
> Fix unjoin system channel

- packages/athena/libs/deployer_lib.js
The operator will take care of restarting the component when the admin_certs field is edited. This PR removes the restart from console.
> remove auto restart when editing specific fields

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- Bug fix
Use correct identity for pulling blocks from orderer
> Unable to join channel from another orderer

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- Bug fix
when joining channel from an orderer cluster, if there are two nodes (one consenter and one follower) and if the follower happens to be the first one, there is a 404. Try getting the channel config block from consenter.
> 404 when joining channel

- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/ChannelModal/Wizard/Admins/Admins.js
- packages/apollo/src/components/ChannelModal/Wizard/OrdererOrganizations/OrdererOrganizations.js
- Bug fix
- fix orderer msp drop down options, removes msps that do not have a known orderer
- fixes update channel flow when system channel less orderer is used, prevents genesis block creation step from appearing
> Filter orderer msps

- packages/athena/libs/deployer_lib.js
- Bug fix
if the `node_ou` field of a component is edited, the console should not send a restart since the operator will already do that
> remove console component auto restarts

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
Adds a toast message after a orderer successfully joins the channel using the channel participation apis.
> show success toast msg when orderer joins channel

- packages/athena/libs/deployer_lib.js
- packages/athena/libs/ot_misc.js
- Bug fix
The systemless orderer append flow should use the `bulk_add_components` logic when onboarding and parsing deployer's create-orderer response. This is b/c deployer responds with an array of components and not an object for this route.
> use "bulk_add_components" for a systemless append

- packages/apollo/src/components/Channels/Channels.js
- Bug fix
A pending channel tile was listing the cluster names once per node, which is redundant. This only lists the cluster names once.
> list each cluster once in pending channel tile

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- packages/apollo/src/components/JoinOSNChannelModal/_joinOSNChannelModal.scss
- Bug fix
- the node options listed during a  systemless-channel orderer join were not as lax as they should be. this pr allows selecting nodes from any cluster that has the same MSP.
> fix the orderer/cluster select options in join wiz

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- packages/apollo/src/components/OrdererDetails/ChannelParticipationDetails.js
- Bug fix
- always add the drill down cluster nodes to the join-orderer-to-channel flow, b/c these nodes should always be valid options.
> always add the selected cluster nodes for joinflow

- packages/athena/libs/deployer_lib.js
- Bug fix
Removes unnecessary component restart on an admin cert change.
> remove restart on admin cert change

- packages/apollo/src/rest/ChannelApi.js
- Bug fix
Handle empty or undefined values for  `Endpoints.value.addresses` in a config block. This fixes an error when joining a peer to a channel that has an orderer org with zero orderers.
> parse config block Endpoints -> addressess safely

- .github/workflows/common.yml
- Test update
Use a specific version of detect secrets to avoid breaking builds when a new one is released.
> pin detect secrets to .52

- packages/apollo/src/rest/MigrationApi.js
- New feature
Adds the missing file on the migration apis introduced by https://github.com/hyperledger-labs/fabric-operations-console/pull/306
> add MigratoinApi.js file in apollo

- docker/console/Dockerfile
- Bug fix
There is some sort of permission error, trying to change the start command from `npm start` to `node server_watcher.js`.
> change start command

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
Signed-off-by: Nikhil Modem <Nikhil.Modem@ibm.com>
- Bug fix
- If an ordering cluster has nodes with the system channel, they were available to add to a channel. The entire cluster should not show up in this case.
- If an ordering cluster has nodes both with and without the system channel, all node were available to add to the channel. The cluster should show up, but only the nodes that do not have a system channel should show up in this case.
- Both of the above scenarios are dealt with by only returning nodes that do not have a system channel, regardless of the overall cluster configuration.
> Bug fix when adding ordering nodes to channel

- packages/apollo/src/components/PageHeader/PageHeader.js
- packages/apollo/src/components/TitleBar/_titleBar.scss
- Bug fix
The new migration banner was left visible, accidentally. It should only show after a console has migrated.
> don't show the migrated console banner

- packages/apollo/src/components/CADetails/CADetails.js
- packages/apollo/src/components/IdentityExpiration/IdentityExpiration.js
Signed-off-by: Nikhil Modem <Nikhil.Modem@ibm.com>
- Bug fix
- Non-admin identity message appeared for associated identities of CAs which didn't make sense so took it out.
-  Also moved PageHeader component on CA details page to reflect other pages. This makes the migration banners present better too.
> non admin didentity message no longer appears on ca details page.

- packages/apollo/src/App.js
- Bug fix
Bring back the setPlatform call in App.js to correctly set the `Helper.infrastructure.platform` field.
> add back the setPlatform call

- packages/apollo/src/rest/NodeRestApi.js
- Bug fix
When updating an MSP, the admin certs on a peer were not being synchronized correctly. Admin certs could be added but not removed. This PR fixes that.
> fix admin cert sync when updating msp

- packages/apollo/src/components/InstantiateChaincodeModal/InstantiateChaincodeModal.js
- packages/apollo/src/components/PageHeader/PageHeader.js
Signed-off-by: Nikhil Modem [Nikhil.Modem@ibm.com](mailto:Nikhil.Modem@ibm.com)
- Bug fix
- Filtering of peers to be used to submit an instantiation or upgrade to was broken due to the way policy msp id's were retrieved from a peer
- Fixed the lodash get to retrieve the identities properly
- Added some logic to the mapping to extract just the msp id string from the Uint8Array that is returned
- Also removed some logging that was left in from a previous PR
> Fixing chaincode instantiation filtering

- packages/apollo/test/functional/features/2-BuildANetwork.feature
- packages/apollo/test/functional/features/9-BuildANetwork_Without_SysChannel.feature
- packages/apollo/test/functional/steps/node.steps.js
- Test update
Added test scenario to created one peer and orderer in 2.2.x and then upgrade them from console to 2.4.x and perform workflow without system channel
> Test case updates to cover 2.2.x to 2.4.x migration via console

- packages/apollo/src/components/ImportCAModal/ImportCAModal.js
- packages/apollo/src/components/ImportOrdererModal/ImportOrdererModal.js
- packages/apollo/src/components/ImportPeerModal/ImportPeerModal.js
- packages/apollo/src/components/JsonInput/JsonInput.js
- packages/apollo/src/rest/CertificateAuthorityRestApi.js
- packages/apollo/src/rest/MspRestApi.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/apollo/src/rest/PeerRestApi.js
- packages/apollo/src/utils/helper.js
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/libs/comp_formatting_lib.js
- New feature
A new field called `migrated_from` will appear (if its populated) in exports, and will be stored if imported. This will track components being moved from one console to another.
> propagate "migrated_from" through export & import

- packages/athena/libs/deployer_lib.js
- Bug fix
This hides selected peer versions that cause issue with node.js chaincode.
> hide fabric verions that break chaincode in peer

- packages/athena/libs/db_backup.js
- packages/athena/public/releaseNotes.json
- Bug fix
During a restore, if a doc doesn't exist it will causes a conflict when writing the doc (paradoxically). this PR fixes that.
> prevent doc conflicts during restore

- packages/apollo/src/components/CADetails/CADetails.js
- packages/apollo/src/components/Chaincodes/Chaincodes.js
- packages/apollo/src/components/ChaincodesPage/ChaincodesPage.js
- packages/apollo/src/components/ChannelChaincode/ChannelChaincode.js
- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
- packages/apollo/src/components/PeerChaincode/PeerChaincode.js
- packages/apollo/src/components/PeerDetails/PeerDetails.js
- packages/athena/json_docs/default_settings_doc.json
- Bug fix
A few buttons were left enabled, this disables them when the console is in read-only mode.
> disable more buttons if in read only mode

- packages/fabric-deployer/deployer/components/ca/ca.go
- packages/fabric-deployer/deployer/components/ca/get.go
- packages/fabric-deployer/deployer/components/ca/mocks/kube.go
- packages/fabric-deployer/deployer/components/orderer/get.go
- packages/fabric-deployer/deployer/components/orderer/mocks/kube.go
- packages/fabric-deployer/deployer/components/orderer/orderer.go
- packages/fabric-deployer/deployer/components/peer/get.go
- packages/fabric-deployer/deployer/components/peer/mocks/kube.go
- packages/fabric-deployer/deployer/components/peer/peer.go
- packages/fabric-deployer/deployer/deployer.go
- packages/fabric-deployer/deployer/kube/kube.go
- Bug fix
- Improvement
* A new endpoint `/api/v3/instance/{serviceInstanceID}/cluster/type` to determine if the cluster is ocp or k8s 
* Added a fix to override endpoints for k8s only and unchange ocp endpoints
> Add endpoint to determine if clustertype is openshift or k8s

- packages/athena/libs/migration_lib.js
- Bug fix
Formats the migrated console url correctly when standard ports like 443 or 80 are used. This fixes logic downstream that attempts to match against this url value.
> format migrated url correctly if standard port

- packages/athena/libs/migration_lib.js
- Bug fix
Newly migrated consoles should not be in the read-only state.
> disable read only state in newly migrated consoles

- packages/athena/libs/migration_lib.js
- packages/athena/libs/pillow_talk.js
- Bug fix
- lets athena safely periodically reconnect to the couchdb _changes api
- it will now reconnect daily
- migration will now reconnect the _changes api when migration has started to ensure the api is alive and well
- ties into more request events to let the couchdb _changes api reconnect when things go wrong
- previously only the events `error` and `end` where used to reconnect, we now use `error`, `end`, `timeout`, `abort`, `close`
> reconnect to couchdb _changes api periodically ++

- packages/athena/libs/ot_misc.js
- packages/athena/routes/other_apis.js
- console restart apis will now log the process id that is restarting
- added restart api that will kill the process (which kills the pod) `ak/api/v[123]/restart/force/hard`
> tidy up console restart apis

- dictionary_blockchain.txt
- packages/athena/app.js
- packages/athena/libs/db_backup.js
- packages/athena/package-lock.json
- packages/athena/package.json
- packages/athena/public/releaseNotes.json
- Improvement
- console database backups will be temporary stored to the filesystem to avoid cloudant size limits
- console database backups will be compressed to minimize transfer sizes during migration
> compress console database backups and use fs

- packages/athena/app.js
- packages/athena/libs/couchdb.js
- packages/athena/libs/misc.js
- packages/athena/libs/ot_misc.js
- packages/athena/libs/other_apis_lib.js
- packages/athena/libs/root_misc.js
- packages/athena/libs/settings.js
- packages/athena/libs/webhook_lib.js
- packages/athena/test/test-suites/common-test-framework.js
- packages/athena/test/test-suites/lib/couchdb.test.js
- Bug fix
With node 18, values of `localhost` are interpreted as their IPv6 equivalent of `::1`, however our couchdb containers are not listening on `::1`, they only work with IPv4. This PR replaces `localhost` on outgoing destinations with `127.0.0.1` to keep things as IPv4.
This fixes database connecting issues (with certain couchdb configurations) seen since build `1.0.5-3`.
> make couchdb url use ipv4 and not ipv6

- packages/athena/libs/db_backup.js
- packages/athena/libs/migration_lib.js
- Bug fix
The migration code that edits the settings doc prior to migration needs to decompress the backup data first. otherwise the edits do not happen and the new console is thrown into shenanigans.
> decompress docs before migration edits settings

- packages/apollo/src/components/Identities/Identities.js
- packages/apollo/src/components/Log/Logger.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/rest/NodeRestApi.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/athena/public/releaseNotes.json
- packages/stitch/src/libs/proto_handlers/block_pb_lib.ts
- packages/stitch/src/libs/proto_handlers/proposal_pb_lib.ts
- packages/stitch/src/libs/validation.ts
- packages/stitch/src/stitch.ts
- Bug fix
lots of performance improvements that are mainly on the orderer modals (the side panel when viewing an orderer), but these changes will bleed over to other pages as well.
- fixed a race condition + nearly infinite loop where page spins getting the fabric version over and over, it would eventually settle after hundreds of requests
- parallelize getting root certs from CAs
- removed redundant API calls getting component details over and over
- removed the recursive behavior on the get-component-details function
- on the orderer modal, it now only calls APIs for functions that are needed for the particular modal function that was opened
- when walking the system channel to discover channel's (for the delete orderer-modal), it …
> fix logic on orderer modals, speed improvement

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/Channels/Channels.js
- New feature
There already exists a query parameter that will show archived pending channel tiles under the orderer section of the channels tab but the only way to do this was by putting in the query, `?visibility=all`, into the address bar. 
Added a button on the orderer channels section of the channels page to toggle between showing and hiding the channels:
> Toggle between to sho/hide archived pending channels

- packages/athena/libs/deployer_lib.js
- packages/athena/test/test-suites/routes/deployer_apis.test.js
- Bug fix
When upgrading fabric, new features might become available. we need to sync the component data after a fabric upgrade.
> sync component data after fabric upgrade

- packages/athena/json_docs/json_validation/ibp_openapi_v2.yaml
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/libs/validation_lib.js
- Bug fix
The safe-url validation code was not working correctly if the legacy field `caport` was used. This only effects the `/v2/` APIs.
> fix safe URL vaildation for legacy field "caport"

- packages/apollo/src/components/JoinChannelModal/JoinChannelModal.js
- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/StitchApi.js
- Bug fix
When joining a peer to a channel (and the anchor peer toggle was enabled) it was failing to add a peer as an anchor peer to the channel.
> fix anchor peer error when joining peer to channel

- packages/athena/libs/component_lib.js
- packages/athena/libs/deployer_lib.js
- packages/athena/public/releaseNotes.json
- packages/athena/test/test-suites/routes/component_apis.test.js
- Bug fix
- After upgrading a fabric node we need to rebuild the internal url safe list
- after editing a component, we should rebuild the internal url  safe list
> rebuild safelist during comp edits/fabric upgrades

- packages/athena/app.js
- Bug fix
The auto renewal of the self signed tls cert code had some copy paste error in it, preventing it from working.
> fix the library name for the self signed tls renew

- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- Improvement
Added check for if a ordering cluster has a system channel to prevent using channel participation api unnecessarily which was slowing down the loading of the orderer details page
> Improve slow loading of orderer details page

- packages/athena/libs/migration_lib.js
- config change
A new console migration will now set `allow_default_password ` as `false`, instead of `true`
> set allow_default_password as false for migration

- packages/athena/libs/comp_formatting_lib.js
- removes the sensitive field `datasource` from component API responses (applies to CA components)
> remove sensitive fields from a CA response

- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/ChannelModal/Wizard/Consenters/Consenters.js
- packages/apollo/src/components/SidePanel/_sidePanel.scss
- packages/athena/json_docs/default_settings_doc.json
- Bug fix
- when editing a channel, the add/remove consenter part was not showing all the orderer nodes as options
> fix orderer node options in consenter input

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/Access/Access.js
- packages/athena/docs/_oauth.md
- packages/athena/libs/auth_scheme_lib.js
- Bug fix
If the console is in read only mode, the access tab will no longer let you change the auth scheme, add/remove users, or add/remove api keys
> if in read-only disable actions in the access tab

- packages/athena/libs/component_lib.js
- Bug fix
- if a component was migrated from an iks cluster, the component status requests were using the new style of "api url" instead of the legacy style. the new style will not work on a legacy migrated component. the result is the status icon of a component in that state never goes green.
> if comp is migrated choose correct route when getting the component status

- packages/athena/routes/deployer_apis.js
The `registry` field in some apis revels sensitive information to users with the manager role, this info is now removed.
> redact registry fields even if manager

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/PeerModal/PeerModal.js
> version check for node warnings

- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/athena/public/releaseNotes.json
- packages/stitch/src/libs/config_block.ts
- Bug fix
- fix front end crash when editing channel consenters when orderer does not use a system channel, `addressess` field in config block might not be set
> fix indexing into addresses if its not set

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
- packages/apollo/src/components/ChannelMembers/ChannelMembers.js
- packages/apollo/src/components/UpdateChannelMspModal/UpdateChannelMspModal.js
- packages/apollo/src/components/UpdateChannelMspModal/_updateChannelMspModal.scss
- New feature
This PR shows/lists the identities from the local wallet that are also admins on the channel, so that the user can make a better informed choice when selecting the identity to use when changing the MSP definition.
> Showing MSP admins present in wallet while updating MSP definition

- packages/apollo/src/components/CADetails/CADetails.js
- packages/apollo/src/components/ItemContainer/ItemContainer.js
> Decoupling register user button from CA users table 

- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
- packages/athena/public/releaseNotes.json
- Bug fix
From the channels page, and the channel details tab, when clicking an orderer node on the channel, the app will now correctly redirect the user to the drill down of that orderer.
> Fix drilldown

- packages/apollo/package-lock.json
- packages/apollo/package.json
Upgrade npm browserify-sign in apollo to 4.2.2 to address https://nvd.nist.gov/vuln/detail/CVE-2023-46234
> Upgrade browserify-sign to 4.2.2 to address CVE.

- packages/apollo/src/components/CADetails/CADetails.js
- packages/apollo/src/components/Chaincodes/Chaincodes.js
- packages/apollo/src/components/ChannelChaincode/ChannelChaincode.js
- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
- packages/apollo/src/components/Channels/Channels.js
- packages/apollo/src/components/Identities/Identities.js
- packages/apollo/src/components/ItemContainer/ItemContainer.js
- packages/apollo/src/components/OrdererAdmins/OrdererAdmins.js
- packages/apollo/src/components/OrdererDetails/ChannelParticipationDetails.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/OrdererMembers/OrdererMembers.js
- packages/apollo/src/components/PeerChaincode/PeerChaincode.js
- packages/apollo/src/components/PeerChannels/PeerChannels.js
- packages/apollo/src/components/PeerDetails/PeerDetails.js
- packages/apollo/src/components/StickySection/StickySection.js
- packages/apollo/src/utils/actionsHelper.js
- Bug fix
Prevents users with only the reader role from doing actions like:
- creating CA identities
- enrolling CA identities
- creating channels
> prevent users with only a reader role from actions

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/Settings/Settings.js
- packages/apollo/src/components/Settings/_settings.scss
- packages/apollo/src/rest/NodeRestApi.js
- packages/apollo/src/utils/helper.js
- packages/athena/libs/component_lib.js
- packages/athena/libs/misc.js
- packages/athena/libs/other_apis_lib.js
- packages/athena/routes/other_apis.js
- New feature
Adds a new button under the `settings` tab. it will generate a json file of all component versions, operator fabric versions, and the console version. this is useful for support.
> Add gather version button

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/Access/Access.js
- packages/apollo/src/components/AddUserModal/AddUserModal.js
- packages/athena/libs/permissions_lib.js
> prevent the last manager from removing manager role

- packages/apollo/src/components/CADetails/CADetails.js
- packages/apollo/src/components/Chaincodes/Chaincodes.js
- packages/apollo/src/components/ChannelAnchorPeers/ChannelAnchorPeers.js
- packages/apollo/src/components/ChannelChaincode/ChannelChaincode.js
- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
- packages/apollo/src/components/Channels/Channels.js
- packages/apollo/src/components/ItemMenu/ItemMenu.js
- packages/apollo/src/components/ItemMenu/_itemMenu.scss
- packages/apollo/src/components/OrdererAdmins/OrdererAdmins.js
- packages/apollo/src/components/OrdererDetails/ChannelParticipationDetails.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/OrdererMembers/OrdererMembers.js
- packages/apollo/src/components/PeerChaincode/PeerChaincode.js
- packages/apollo/src/components/PeerChannels/PeerChannels.js
- packages/apollo/src/components/PeerDetails/PeerDetails.js
- packages/apollo/src/components/StickySection/StickySection.js
- packages/apollo/src/index.scss
- packages/apollo/src/utils/actionsHelper.js
- packages/apollo/src/utils/constants.js
- packages/apollo/test/unit/tests/CADetails.test.jsx
- packages/apollo/test/unit/tests/CAModal.test.jsx
- packages/apollo/test/unit/tests/CertificateAuthority.test.jsx
- packages/apollo/test/unit/tests/Settings.test.jsx
- packages/athena/docs/_permissions.md
- Bug fix
- users that are readers can no longer:
-  delete CA identities
- install smart contracts
- remove ordering service consenters from an app channel
- add anchor peers to an app channel
> fix user roles/permissions on fabric operations

- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- Bug fix
Users of the console with the `writer` role should be able to import ordering service nodes to an existing OS. currently the button is disabled/hidden.
> allow a writer to import an OS node

- packages/apollo/src/utils/helper.js
- packages/athena/public/releaseNotes.json
- Bug fix
The change in https://github.com/hyperledger-labs/fabric-operations-console/pull/573/files sets the location field differently which breaks exporting/importing components. Undoing.
> reverting 573 b/c of broken export/import flow

- packages/athena/libs/request_axios.js
- packages/athena/package-lock.json
- packages/athena/package.json
- packages/athena/test/axios.js
- packages/stitch/package-lock.json
- Bug fix
- The axios wrapper introduced in `1.0.8-4` was copying the `body` filed to `data`, and then deleting `body` which led to errors when the code later tried to use `body`. This error surfaced in the UI with newly created components having blank names/tiles. Other internal fields were also missing.
- also fixes some npm dependency cves
> prevent the axios wrapper from deleting body arg

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- packages/apollo/src/utils/constants.js
- packages/athena/libs/request_axios.js
- packages/stitch/docs/README.md
- Bug fix
- fixes https requests that require mutual tls. Such as the orderer's channel participation apis. These APIs were failing because our `request` module replacement, `axios`, was not sending the client side tls cert.
- fixes our error response handling of the channel participation api `getOSNChannel`. will now correctly indicate an error occured.
> fix mutual tls reqs with axios http lib

- packages/athena/libs/proxy_lib.js
Lowers the cache expiration of component status APIs from 120 seconds to 90 seconds.
> reduce cache expiration from 2 minutes to 1.5 minutes

- packages/apollo/src/components/ImportCAModal/ImportCAModal.js
- packages/apollo/src/components/ImportCAModal/_importCAModal.scss
- packages/apollo/src/components/ImportOrdererModal/ImportOrdererModal.js
- packages/apollo/src/components/ImportOrdererModal/_importOrdererModal.scss
- packages/apollo/src/components/ImportPeerModal/ImportPeerModal.js
- packages/apollo/src/components/ImportPeerModal/_importPeerModal.scss
- packages/apollo/src/components/Wizard/Wizard.js
- packages/apollo/src/utils/actionsHelper.js
- packages/apollo/src/utils/constants.js
- Bug fix
- in the import/deploy component modal for CAs, peers, and OS's, it was defaulting to the deploy flow, even if that choice was not available
- the app was hiding the deploy option if it was not available, but it will now show as a disabled choice
> Fix create component modals - default choice

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- packages/apollo/src/utils/helper.js
- Clean up
zip files and json files that were downloaded used a legacy prefix of `IBP`, changing that to `FOC`. 
- example filename with this PR: `FOC.1-26-2024-42454.zip`
> change the prefixes found on exported files to FOC instead of IBP

- packages/athena/libs/component_lib.js
- packages/athena/libs/patch_lib.js
- packages/athena/libs/proxy_lib.js
- packages/athena/public/releaseNotes.json
- packages/athena/routes/deployer_apis.js
- packages/athena/test/test-suites/routes/deployer_apis.test.js
- Bug fix
Fixes the mustgather download zip button, the previous route for this download was using a `request.get` and a `pipe` method which are not available in our axios-request wrapper.
this fix does require rebuilding the URL allow list, which will happen on startup automatically
> fixes mustgather download button w/axios

- packages/fabric-deployer/go.mod
- packages/fabric-deployer/go.sum
CVE-2022-1996: https://nvd.nist.gov/vuln/detail/CVE-2022-1996
> Address CVE-2022-1996. emicklei/go-restful.

- packages/athena/libs/other_apis_lib.js
- packages/athena/test/openapi/init_examples.js
- Bug fix
YAML to JSON parsing was broken, `safeDump()` is not longer in the yaml library.
> fixes yaml parsing

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- packages/apollo/src/components/OrdererDetails/ChannelParticipationUnjoinModal.js
- packages/apollo/src/rest/EventsRestApi.js
- Bug fix
- Update audit log message and status code while fail to add peers to channel.
- Add Audit log entry on Join Orderer peer to existing channel
- Add Audit log entry on disconnect orderer peer from channel
> Update audit log message while fail to adding peers to channel

- packages/athena/app.js
- Improvement (security)
- adding `object-src 'none'` to our CSP response header, this will be on all non-cached responses (cached responses already have it)
> add object-src to the csp header in all api responses

- packages/fabric-deployer/go.mod
- packages/fabric-deployer/go.sum
As per https://github.com/advisories/GHSA-jq35-85cj-fj4p, need to update/upgrade to latest Golang package for github.com/docker/docker.
> Fix github.com/docker/docker vulnerability as per GHSA-jq35-85cj-fj4p.

- packages/apollo/src/components/ProposeChaincodeModal/ProposeChaincodeModal.js
- Cleanup update
Removing the legacy `init_required` input option when making a chaincode definition (only applies to the 2.0 lifecycle). It will now always be `false`.
> remove init required input option in chaincode lifecycle 2.0

- packages/apollo/src/components/ChaincodeModal/ChaincodeModal.js
- packages/apollo/src/components/InstantiateChaincodeModal/InstantiateChaincodeModal.js
- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/StitchApi.js
the improvements below help if 1 or more orderers is in a bad state, but the remaining orderers still have consensus:
- if chaincode instantiation or upgrade fails it will now retry the transaction for each consenting orderer node
- if approving a chaincode definition fails, it will now retry the transaction for each consenting orderer node
- if commiting a chaincode definition fails, it will now retry the transaction for each consenting orderer node
> retry chaincode transactions with all orderers

- packages/apollo/src/components/Channels/Channels.js
- Bug fix
- In channel listing show same ordering cluster name show in both Grid and List view
- In channel listing show distinct ordering cluster name
> Show distinct ordering cluster name and same value display in Grid and List view

- packages/apollo/test/cypress/e2e/features/04-CreateAndJoin2x_Org1AndOrg2.feature
- packages/apollo/test/cypress/e2e/features/09-BuildANetwork_Without_SysChannel.feature
- packages/apollo/test/cypress/e2e/features/12-AuditLog.feature
- packages/apollo/test/cypress/e2e/features/13-ConsoleAPI.feature
- packages/apollo/test/cypress/support/commands.js
- packages/apollo/test/cypress/support/step_definitions/navigation_steps.js
- packages/apollo/test/cypress/support/step_definitions/notifcation_steps.js
- Test update
1 - Updated Channel creation to use 2.0 ordering capability option
2 - Added new test to check for Audit logs for API key creation and deletion
3 - Fix as per pipeline failure
> 2.0 ordering capability channel and fixes to failures

- README.md
- packages/athena/libs/deployer_lib.js
- packages/athena/libs/other_apis_lib.js
- Bug fix
When we download version summary from the settings in the console, in the operator part CA version was coming wrong. So, the changes will help to generate correct version of CA in the Version Summary Module of the console.
> fix version summary module, in the summary now it shows correct CA version in operator part

- packages/fabric-deployer/config/config.go
- packages/fabric-deployer/config/config_struct.go
- packages/fabric-deployer/config/config_test.go
- packages/fabric-deployer/deployer/components/peer/get.go
- packages/fabric-deployer/deployer/components/peer/get_test.go
- packages/fabric-deployer/deployer/components/peer/patch_test.go
- packages/fabric-deployer/deployer/components/peer/peer.go
- packages/fabric-deployer/deployer/components/peer/peer_test.go
- packages/fabric-deployer/deployer/components/peer/update_test.go
- packages/fabric-deployer/deployer/deployer_test.go
- packages/fabric-deployer/docs/v3_apis.md
- packages/fabric-deployer/docs/v3_responses/versions_all.json
- packages/fabric-deployer/docs/v3_responses/versions_peer.json
- packages/fabric-deployer/sampleconfigs/local-config.yaml
- Improvement (Code Cleanup)
We had references of DIND in the deployer code which is deprecated and no longer needed in fabric 2x. Hence removed all the references of DIND from codebase
> Removed DIND References from Deployer

- packages/fabric-deployer/go.mod
- packages/fabric-deployer/go.sum
[CVE-2024-24786](https://nvd.nist.gov/vuln/detail/CVE-2024-24786)
> Upgrade google.golang.org/protobuf for CVE-2024-24786.

- packages/athena/libs/component_lib.js
- New feature
the console currently uses the field migrated_from="ibm_saas" to decide if it should use the legacy (saas) set of urls to communicate to the component, or the opensource-operator styled urls. this change allows a new field called preferred_url to be set (per component) to "os", which would allow a migrated(saas) component to return with the open-source style of urls.
> "preferred_url" - The style/format of a url to return for a migrated component. Does not apply to non-migrated components. Set to "os" to return open-source operator urls for these field: api_url, operations_url and osnadmin_url. Otherwise migrated components will return the legacy ("saas") style urls.
- effects apis like:
- get-component
- get-all-components
> added condition for migrated component to return os style urls

- docker/console/Dockerfile
It's premature to move to UBI-9 at the moment and causes too many issues with build process.  The other changes can stay and remain helpful improvements.
> Revert to UBI8 for now.

- packages/fabric-deployer/go.mod
- packages/fabric-deployer/go.sum
Address latest docker/docker vulnerability in Fabric Deployer APIs.
> Upgrade github.com/docker/docker to v25.0.5 to address CVE-2024-29018.

- packages/apollo/src/App.js
- packages/apollo/src/components/CAModal/CAModal.js
- packages/apollo/src/components/ChannelConsenterModal/ChannelConsenterModal.js
- packages/apollo/src/components/DeleteCAUser/DeleteCAUserModal.js
- packages/apollo/src/components/GenerateMSPModal/GenerateMSPModal.js
- packages/apollo/src/components/IdentityModal/IdentityModal.js
- packages/apollo/src/components/Login/Login.js
- packages/apollo/src/components/MSPDefinitionModal/MSPDefinitionModal.js
- packages/apollo/src/components/Main/Main.js
- packages/apollo/src/components/MspDeleteModal/MspDeleteModal.js
- packages/apollo/src/components/OrdererConsenterModal/OrdererConsenterModal.js
- packages/apollo/src/components/OrdererDetails/ChannelParticipationUnjoinModal.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/PeerModal/PeerModal.js
- packages/apollo/src/components/RenderHTML/RenderParamHTML.jsx
- packages/apollo/src/components/SignatureDetailModal/SignatureDetailModal.js
- Bug fix
Landing page issue and clipboard with localisation issue fix
> update landing page issue and clipboard with localizaton fix

- docker/console/Dockerfile
- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/BlockchainTooltip/BlockchainTooltip.js
- packages/apollo/src/components/CADetails/CADetails.js
- packages/apollo/src/components/ChannelModal/_channelModal.scss
- packages/apollo/src/components/Form/Form.js
- packages/apollo/src/components/GenerateCertificate/GenerateCertificateModal.js
- packages/apollo/src/components/NodeDetails/NodeDetails.js
- packages/apollo/src/components/Nodes/_nodes.scss
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/PeerDetails/PeerDetails.js
- packages/apollo/src/index.scss
- Bug fix
- HTML Rendering issue on re-enroll user
- UI issue on peer detail page
- Ordering service node detail page loading issue
- Blank Ordering Service page is displayed navigating from ordering service node page
- Add button alignment issue in Create Channel -> Organisations screen
> library update issue fixes

- packages/athena/libs/middleware/middleware.js
- packages/athena/routes/permission_apis.js
- Bug fix
Reader and Writer role user is now able to get bearer token details for the token generated with their API Key
> fix reader writer unable to get bearer token details

- packages/apollo/src/components/CADetails/CADetails.js
- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/PeerDetails/PeerDetails.js
- packages/apollo/src/components/SidePanelError/_sidePanelError.scss
- packages/apollo/src/index.scss
- Update tab ui as per previous console
> updated tab ui as per previous console

- docker/console/Dockerfile
Update ubi8 to nodejs20
registry.access.redhat.com/ubi8/nodejs-20
nodejs 20 update
Update ubi8 to nodejs20
registry.access.redhat.com/ubi8/nodejs-20
> Update ubi8 to nodejs20

- packages/apollo/package-lock.json
- packages/stitch/package-lock.json
- packages/stitch/package.json
ran npm audit fix  command to fix CVE-2024-43788 - webpack and micromatch version because the checks were failing in PR
https://github.ibm.com/ibp/OpTools/issues/6150
> fix for CVE-2024-43788 - webpack

- packages/athena/package-lock.json
- packages/stitch/package-lock.json
ran npm audit fix to address multiple package updates including 
- serve-static (CVE-2024-43800)
- send (CVE-2024-43799)
- path-to-regexp-0.1.7.tgz )(CVE-2024-45296)
- express-4.19.2.tgz (CVE-2024-43796)
- body-parser-1.20.2.tgz (CVE-2024-45590)
> Multiple package updates

- packages/athena/libs/ca_lib.js
- packages/athena/libs/fabric_ca_services/fabric_utils.js
When interacting with Fabric CA REST services,
utilize the updated auth header token format
that includes the URL path and method.
The old format has been deprecated for a long time (since Fabric CA v1.4.0) since the new format is more secure. New versions of Fabric CA (v1.5.14 and later) will not support the old format by default (although they can still support the old format by setting `FABRIC_CA_SERVER_COMPATIBILITY_MODE_V1_3=true`).
For reference see similar change in legacy Node SDK that never got propagated to the console Fabric CA client:
https://github.com/hyperledger/fabric-sdk-node/commit/602f557cc9fa07d444bb707aeef4eb3b94757779
And the original change in Fabric CA that is driving this change:
https://github.com/hyperledger/fabric-ca/commit/99517e9d983750e7e8c9a8db9eeda7008e37d7 …
> Update auth header token for CA

- packages/stitch/src/libs/ca_lib.ts
- packages/stitch/src/libs/crypto_misc.ts
When interacting with Fabric CA REST services,
utilize the updated auth header token format
that includes the URL path and method.
The old format has been deprecated for a long time (since Fabric CA v1.4.0) since the new format is more secure.
New versions of Fabric CA (v1.5.14 and later) will not support the old format by default
(although they can still support the old format by setting FABRIC_CA_SERVER_COMPATIBILITY_MODE_V1_3=true).
For reference see similar change in legacy Node SDK that never got propagated to the console Fabric CA client:
https://github.com/hyperledger/fabric-sdk-node/commit/602f557cc9fa07d444bb707aeef4eb3b94757779
And the original change in Fabric CA that is driving this change:
https://github.com/hyperledger/fabric-ca/commit/99517e9d983750e7e8c9a8db9eeda7008e37d7ff …
> Update auth header token for CA (stitch)

- scripts/setupNetwork.sh
Improve setupNetwork.sh for local environments.
- Use the latest fabric installer (pulls from ghcr for latest images, avoiding dockerhub pull limit errors)
- Use the latest fabric version (v2.5.11) and fabric ca version (v.1.5.15)
- Default to samples main branch unless version v2.2.x is downloaded
- Make chaincode deploy optional (commented out)
> Improve setupNetwork

- packages/athena/libs/other_apis_lib.js
- Bug fix
When a user updates default password in authentication settings on the Access page, there is strong password validation on the client side. However, this can easily be bypassed with proxy tool. The new added code is to ensure strong password checks also enforced on the server side.
> fix bypass client side validation for default password

- scripts/setupConsole.sh
- Bug fix
It looks like the old docker-compose syntax is no longer supported. On a fresh install of docker and the docker compose plugin, this error will occur https://github.com/hyperledger-labs/fabric-operations-console/issues/847. This PR updates to the updated syntax of `docker compose` and resolves this error.
> Support newer versions of docker compose plugin

- MAINTAINERS.md
This repository did not previously have a MAINTAINERS.md file.
Therefore this commit adds the MAINTAINERS.md file and adds Thomas.
> Nominate Thomas Leung as Maintainer

- packages/apollo/package-lock.json
Bump sha.js and cipher-base
CVE-2025-9288 - Improper Input Validation vulnerability in sha.js allows Input Data Manipulation.This issue affects sha.js: through 2.4.11.
CVE-2025-9287 - Improper Input Validation vulnerability in cipher-base allows Input Data Manipulation.This issue affects cipher-base: through 1.0.4.
> Bump sha.js and cipher-base
