hyperledger-labs/fabric-operations-console

- .github/workflows/apollo.yml
- .github/workflows/athena.yml
- .github/workflows/common.yml
- .github/workflows/deploy.yml
- .github/workflows/grpc-web-docker.yml
- .github/workflows/stitch.yml
> add github actions

- .github/workflows/deploy.yml
> enable image push

- .github/workflows/deploy.yml
- docker/publish_image.sh
> fix image build

- docs/_config.yml
> fix git link in docs

- packages/apollo/.secrets.baseline
- packages/athena/.secrets.baseline
- packages/athena/app.js
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/libs/component_lib.js
- packages/athena/libs/deployer_lib.js
- packages/athena/libs/misc.js
- packages/athena/libs/ot_misc.js
- packages/athena/libs/patch_lib.js
- packages/athena/libs/settings.js
- packages/athena/test/test-suites/lib/misc.test.js
- packages/stitch/.secrets.baseline
sync with athena to pick up https://github.ibm.com/IBM-Blockchain/athena/pull/1085
> auto fabric upgrade

- packages/apollo/.secrets.baseline
- packages/athena/.secrets.baseline
- packages/athena/json_docs/json_validation/ibp_openapi_v2.yaml
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/package.json
- packages/stitch/.secrets.baseline
https://github.ibm.com/IBM-Blockchain/OpTools/issues/4787
> remove deployer related apis in swagger

- CODE_OF_CONDUCT.md
- packages/apollo/.secrets.baseline
- packages/athena/.secrets.baseline
- packages/stitch/.secrets.baseline
> add code of conduct

- docker/console/Dockerfile
> create image from redhat ubi

- packages/athena/libs/comp_formatting_lib.js
- packages/athena/libs/deployer_lib.js
- packages/athena/libs/ot_misc.js
> when no fabric ver is in body, detect the default

- packages/athena/json_docs/default_settings_doc.json
> make db compaction disabled by default

- packages/apollo/.secrets.baseline
- packages/apollo/src/components/ChaincodeModal/ChaincodeModal.js
- packages/apollo/src/components/ProposeChaincodeModal/ProposeChaincodeModal.js
- packages/apollo/src/utils/helper.js
- packages/athena/.secrets.baseline
- packages/stitch/.secrets.baseline
> calculate package id

- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/PeerRestApi.js
> support for newer type of orderer addresses

- packages/athena/json_docs/default_settings_doc.json
- packages/athena/json_docs/json_validation/ibp_openapi_v2.yaml
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/libs/comp_formatting_lib.js
- packages/athena/test/test-suites/routes/deployer_apis.test.js
addresses https://github.com/hyperledger-labs/fabric-operations-console/issues/74
> allow underscores and dashes in comp id field

- FAQ.md
- README.md
- packages/athena/README.md
- packages/athena/env/README.md
- packages/stitch/docs/README.md
adds documentation for a few issues like:
- https://github.com/hyperledger-labs/fabric-operations-console/issues/70
> improve readme, add crypto secure context details

- packages/athena/env/README.md
Addresses concern in https://github.com/hyperledger-labs/fabric-operations-console/issues/35
- doc update
> clarify purpose of the confusing password fields

- packages/athena/docs/_event_tracking_notes.md
- packages/athena/env/README.md
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/libs/activity_tracker.js
- packages/athena/libs/settings.js
- packages/athena/test/test-suites/common-test-framework.js
- packages/athena/test/test-suites/lib/activity_tracker.test.js
for issue https://github.com/hyperledger-labs/fabric-operations-console/issues/42. 
i've repurposed the "Activity Tracker" code to work in a more generic way and use a simpler format. Also this enables the audit logs by default.
> add changes to enable and doc audit log files

- packages/athena/public/releaseNotes.json
> added to release notes

- FAQ.md
- README.md
- docs/apis.md
- packages/athena/docs/permission_apis.md
- packages/athena/env/README.md
- packages/athena/libs/patch_lib.js
https://github.com/hyperledger-labs/fabric-operations-console/issues/80
> add api doc details

- packages/athena/libs/db_backup.js
The backup api had a doc conflict issue. The previous backup's `_rev` was being kept around instead of resetting. This error would prevent a db backup from being saved.
> prevent doc conflicts during backup api

- packages/stitch/package-lock.json
- packages/stitch/package.json
Fixes error introduced in the latest stitch. `Buffer is not defined`
> update stitch deps to fix buffer issue

- packages/athena/app.js
I noticed some of the long lived timeouts and intervals set in `app.js` were not protected from being set multiple times. Under normal circumstances they shouldn't be created more than once... however this PR will make sure that only 1 timeout/interval will be set.
> prevent setting multiple timeouts and intervals

- packages/apollo/src/components/ChaincodeModal/ChaincodeModal.js
> fix commit flow - org without signature

- packages/apollo/src/utils/helper.js
- packages/athena/app.js
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/libs/middleware/middleware.js
- packages/athena/libs/other_apis_lib.js
- packages/athena/libs/settings.js
- packages/athena/test/test-suites/lib/middleware.test.js
read only mode will allow users to view/monitor components/ledger, but they will be unable to create new or edit existing components.
> add a read-only-mode server setting

- packages/athena/public/releaseNotes.json
> updated release notes

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
> issues template

- packages/apollo/src/assets/i18n/en/messages.json
> add mustgather strings to localization file

- packages/athena/public/releaseNotes.json
- release notes
- updated release notes
> 1208-releasenotes

- packages/athena/public/releaseNotes.json
> update release notes

- packages/athena/libs/patch_lib.js
- use the same major and minor versions for upgrade
> use the same major and minor versions for upgrade

- packages/athena/libs/comp_formatting_lib.js
- packages/athena/libs/component_lib.js
- packages/athena/libs/deployer_lib.js
- packages/athena/test/test-suites/lib/component_lib.test.js
don't merge yet - saving code for next week
- Improvement - will log that we created a random deployer component id.
this helps us debug where the id came from.
> add prefix to random ids and log it

- packages/athena/libs/comp_formatting_lib.js
- Improvement 
adds log message that the deployer id came from the api request.
> log if the deployer id came from the api

- packages/apollo/src/rest/NodeRestApi.js
- Bug fix
This PR fixes the "fabric upgrade available" code if the component is using a short hand version field. 
Older components may have a version of `"v1.4"` instead of the major.minor.patch-prerelease format like `"1.4.5-6"`. The short hand version fields break the "upgrade available" logic (it won't prompt for a fabric upgrade).
> fix the available fabric upgrade  w/old versions

- packages/apollo/package-lock.json
- packages/athena/package-lock.json
- packages/athena/public/releaseNotes.json
- Dependency updates
Updated npm deps.
> update npm deps

- packages/athena/json_docs/json_validation/ibp_openapi_v2.yaml
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- Bug fix
- this allows users to edit the `msp` field
> allowing editing of msp field on imported comps

- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/components/PeerModal/PeerModal.js
- Bug fix
Unable to associate with intermediate ca
> fix intermediate ca - association

- packages/apollo/src/rest/NodeRestApi.js
- packages/apollo/src/rest/StitchApi.js
- packages/stitch/docs/README.md
- packages/stitch/package.json
- packages/stitch/src/libs/fabric_rest.ts
- packages/stitch/src/stitch.ts
- New feature
- adds osnamin apis
- get channels
- get channel
- join channel - not working
- unjoin channel
adds code to eventually support the osnadmin apis on console
> initial osnadmin apis

- packages/apollo/src/rest/ChannelParticipationApi.js
- packages/apollo/src/rest/StitchApi.js
- packages/athena/app.js
- packages/athena/docs/proxy_apis.md
- packages/athena/libs/proxy_lib.js
- packages/athena/routes/proxy_apis.js
- packages/stitch/src/libs/fabric_rest.ts
- New feature
- fixes join channel via osnadmin endpoint
- adds new a generic proxy route w/mutual tls support & multipart content type support
> Fixup join channel via osnadmin

- packages/apollo/package.json
- packages/athena/package.json
- packages/athena/public/releaseNotes.json
- packages/stitch/package.json
- Bug fix
- Release Notes
The `license` field wasn't an acceptable value, technically. 
Also updated release notes...
> make license field compliant

- packages/athena/public/releaseNotes.json
- release note fix
change version of release
> update release note

- packages/apollo/src/rest/ChannelParticipationApi.js
- packages/athena/libs/comp_formatting_lib.js
- packages/athena/libs/component_lib.js
- New feature
stores the osnadmin url in console's component doc
> store the osnadmin url

- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- Bug fix
allow setting and editing of `osnadmin_url`
> add osnadmin_url in validator

- packages/apollo/src/components/ImportModal/ImportModal.js
- packages/apollo/src/components/ImportOrdererModal/ImportOrdererModal.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/apollo/src/utils/helper.js
> allow export import admin endpoint from UI

- packages/apollo/src/components/ImportModal/ImportModal.js
> fix bulk import

- packages/apollo/src/components/OrdererDetails/ChannelParticipationDetails.js
- packages/athena/env/dev.json
Signed-off-by: Varad Ramamoorthy <varad@Varads-MacBook.local>
- Improvement
> sort list of nodes for unjoin

- packages/athena/app.js
- packages/athena/package-lock.json
- Bug fix
- remove stack trace generated by express
> remove stack trace from express

- dictionary_blockchain.txt
- packages/apollo/package.json
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/athena/env/README.md
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/package.json
- packages/stitch/package.json
- Improvement / Bug Fix
- added feature flag `osnadmin_feats_enabled` to enable channel participation features based on the osnadmin endpoint
- fixed system channel detection in orderer panel
- add description for all feature flags!
> adds a feature flag for osnadmin

- packages/apollo/test/functional/features/2-BuildANetwork.feature
- packages/apollo/test/functional/features/3-JoinANetwork.feature
- packages/apollo/test/functional/features/4-CreateAndJoin2x_Org1AndOrg2.feature
- packages/apollo/test/functional/features/5-Install20SmartContract.feature
- packages/apollo/test/functional/features/8-InstallInstantiate1xSmartContract.feature
- packages/apollo/test/functional/steps/identity.steps.js
- packages/apollo/test/functional/steps/input.steps.js
- packages/apollo/test/functional/steps/navigation.steps.js
- Bug fix
- Test update
1. Added wait / sleep in feature file step and in code at few places so that it waits for UI to complete the operation
2. Added new method to select text from dropdown with exact text as the existing method was not working if the text has multiple words
> IBP Console UI test case fixes

- packages/apollo/test/functional/features/2-BuildANetwork.feature
- packages/apollo/test/functional/features/3-JoinANetwork.feature
- packages/apollo/test/functional/features/4-CreateAndJoin2x_Org1AndOrg2.feature
- packages/apollo/test/functional/features/8-InstallInstantiate1xSmartContract.feature
Signed-off-by: Ketul Shah shah.ketul@ibm.com
- Test update
1. Added one explicit wait in 8-InstallInstantiate1xSmartContract.feature
2. Updated "2.2" to "2.4.3" to be selected from Fabric dropdown as per 2.5.3 images
> Changes as per 2.5.3 images

- packages/apollo/src/rest/ChannelParticipationApi.js
> fix merge logic - missing channel if the last node didnt have it

- packages/apollo/src/rest/OrdererRestApi.js
- Bug fix
The old code was firing all the import orderer node reqs at once, this PR will send them one at a time.
> import orderers one by one

- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- New feature
Allow editing the `ledger` config field in a peer config yaml.
> allow editing the "ledger" fabric yml config_override field

- packages/apollo/test/functional/features/1-Login.feature
- packages/apollo/test/functional/features/2-BuildANetwork.feature
- packages/apollo/test/functional/features/3-JoinANetwork.feature
- packages/apollo/test/functional/helpers/login.js
- packages/apollo/test/functional/protractor.conf.js
- packages/apollo/test/functional/steps/input.steps.js
- packages/apollo/test/functional/steps/login.steps.js
- Test update
1 - Updated login feature file to login with automation user set in parameter
2 - Updated scenario to select Fabric Version with matching text instead of exact matching the version
3 - Added new step definition for above two points
4 - Added logging statement in login functions for pipeline execution troubleshooting for prod
5 - Added automation default password parameter in protractor.conf file
> Apollo test case fixes

- packages/apollo/src/components/ImportCAModal/ImportCAModal.js
> change version to fabric version

- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/ChannelModal/Wizard/ACL/ACL.js
- packages/apollo/src/components/ChannelModal/Wizard/BlockCuttingParams/BlockCuttingParams.js
- packages/apollo/src/components/ChannelModal/Wizard/Capabilities/Capabilities.js
- packages/apollo/src/components/ChannelModal/Wizard/Prerequisites/Prerequisites.js
- packages/apollo/src/rest/ChannelApi.js
- Bug fix
- fixes the step enable/disable logic in the advanced create channel wizard
> fix the advanced create channel step logic

- packages/apollo/test/functional/helpers/login.js
- packages/apollo/test/functional/steps/login.steps.js
- Test update
Added check for IBM Cloud login - w3id login
> Added check for IBM Cloud login - w3id login

- packages/athena/libs/validation_lib.js
- packages/athena/public/releaseNotes.json
- packages/athena/routes/deployer_apis.js
- Bug fix
Same fix as https://github.com/hyperledger-labs/fabric-operations-console/pull/205 but this PR fixes the update component api.
> Update safelist comp update

- packages/apollo/test/functional/helpers/login.js
- packages/apollo/test/functional/steps/login.steps.js
- Test update
Added more logging around login for Saas and Software scenarios for pipeline troubleshooting
> Added more logging around login for Saas and Software scenarios

- packages/apollo/test/functional/helpers/login.js
- packages/apollo/test/functional/steps/login.steps.js
- Test update
Added logging for login failures in pipeline execution
> Added logging for login failures in pipeline execution

- packages/apollo/src/components/SignatureNotification/_signatureNotification.scss
- Bug fix
The audit notification button was styled in a way that made it invisible.
> restyle audit button so its not invisible

- packages/apollo/src/components/PeerModal/PeerModal.js
Remove the part of the error message that only applies if you were using the APIs.
> remove the confusing part of the error message

- packages/apollo/test/functional/helpers/login.js
- packages/apollo/test/functional/steps/login.steps.js
- Test update
Removed extra logging added
> Removed extra logging added

- packages/apollo/test/functional/features/8-InstallInstantiate1xSmartContract.feature
- packages/apollo/test/functional/helpers/login.js
- packages/apollo/test/functional/steps/login.steps.js
- packages/apollo/test/functional/steps/node.steps.js
Added 2FA code, removed console logs and failure fixes
- Test update
Added 2FA code, removed console logs and failure fixes from pipeline executions
> Added 2FA code, removed console logs and failure fixes

- packages/stitch/package-lock.json
- Dep updates
Npm dependency updates
> npm updates for stitch

- .github/workflows/apollo.yml
- packages/apollo/test/functional/features/8-InstallInstantiate1xSmartContract.feature
- packages/apollo/test/functional/helpers/navigation.js
- packages/apollo/test/functional/steps/chaincode.steps.js
- packages/apollo/test/functional/steps/notifcation.steps.js
- Test update
Increased timeout as per pipeline execution failures / timeout errors
> Increased timeout as per staging environment execution

- packages/athena/env/README.md
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/public/releaseNotes.json
- New feature
set default value for `osnadmin_feats_enabled` as `true`, was `false`
> set default value for osnadmin_feats_enabled as true

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- Bug fix
Only join the orderers that were checked to the channel
> only join selected orderers to channel

- packages/apollo/public/index.html
- packages/apollo/src/components/Login/Login.js
- Bug fix
The browser's title bar on the login page was not always correct
> fix title bar on login page

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/OrdererDetails/ChannelParticipationDetails.js
- packages/apollo/src/components/OrdererDetails/ChannelParticipationUnjoinModal.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/StickySection/_stickySection.scss
- packages/apollo/src/rest/ChannelParticipationApi.js
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- Bug fix
- Fix the with or without system channel detection in the orderer details page
- Adds orderer type to side panel in orderer details page
- Fix the loading logic in the orderer details page
- Updates the node's `systemless` field after removing system channel
> Fix systemless detection

- FAQ.md
- README.md
- docs/system_channel_removal.md
added the system channel removal doc
> added the system channel removal doc

- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/ChannelModal/Wizard/Consenters/Consenters.js
- packages/apollo/src/components/ChannelModal/Wizard/Review/Review.js
- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- New feature
- show the consenter node ids in the review panel of the create channel wizard.
- surface block parsing or getting errors in join osn wizard
> add the consenters to review step of create channel wizard

- packages/apollo/test/functional/features/2-BuildANetwork.feature
- packages/apollo/test/functional/steps/orderer.steps.js
- Test update
Updated test case to create orderer with system channel
> Updated test case to create orderer with system channel

- .github/workflows/athena.yml
- packages/athena/package-lock.json
- packages/athena/package.json
> npm dep updates

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
Added error message when doing a osn admin join and there are no channels to use.
> add error msg when there are 0 channels for join

- docs/system_channel_removal.md
Added a `Console differences with no system channel` section
> improve system channel readme

- packages/apollo/src/components/OrdererModal/OrdererModal.js
- Bug fix
orderer details crashes
> fix orderer detail crash

- packages/athena/json_docs/default_settings_doc.json
- Bug fix
- New feature
- Test update
> update osn feature to false by default

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/Channels/_channels.scss
- packages/athena/json_docs/default_settings_doc.json
- added text to pending channel tile
- fliped osnadmin_feats_enabled feature flag to true
> Join orderer text

- .github/workflows/athena.yml
- .github/workflows/stitch.yml
- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- packages/stitch/src/libs/validation.ts
If we failed to get a config block b/c of a 503 code, display a better error message.
> Improve msg failed config block

- packages/apollo/src/components/ChannelModal/ChannelModal.js
- Bug fix
The update channel wizard button was launching the create channel wizard.
> fix update channel wizard launch

- packages/apollo/src/app.scss
- packages/apollo/src/components/ChannelModal/_channelModal.scss
- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- packages/apollo/src/components/JoinOSNChannelModal/_joinOSNChannelModal.scss
Signed-off-by: Nikhil Modem [nikhil.modem@ibm.com](mailto:nikhil.modem@ibm.com)
- Bug fix
- Imported the new joinOSNChanelModal scss to app.scss so that styles are actually applied now.
- Removed the corresponding styles from the channelModal scss file.
- Fixed the alignment of the name of the node and the checkbox to be inline.
> Fix join orderer text alignment

- packages/athena/libs/deployer_lib.js
- Bug fix
Fixes the route and body to use for the request to append a new orderer node to an os without a system channel.
> fix route and body for appending to systemless os

- packages/apollo/src/components/OrdererModal/OrdererModal.js
Signed-off-by: selvaprakash92 <selvaprakash92@gmail.com>
- Bug fix
orderer associate admin identity label update
> orderer associate admin identity label update

- packages/apollo/src/components/Form/_form.scss
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- Bug fix
Fix the channel tiles when a single orderer is selected. (drill down)
> fix channel list when single orderer is selected

- packages/apollo/src/components/ChannelModal/ChannelModal.js
- Bug fix
Some back buttons on the create wizard would put the user on the wrong step.
> fix back buttons on create channel wizard

- packages/apollo/src/components/ChaincodesPage/_chaincodesPage.scss
- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/ChannelModal/Wizard/OrdererOrganizations/OrdererOrganizations.js
- packages/apollo/src/components/Form/Form.js
- packages/apollo/src/components/ItemContainer/_itemContainer.scss
- packages/apollo/src/components/SidePanel/_sidePanel.scss
- Bug fix
- fix the policy error on the review step of the create wizard if multiple orderer orgs were selected
- fix graphic/image sizes (the size changed due to differences between esbuild and react-scripts)
- fix button widths, prevent overlap
> Various fixes

- packages/apollo/src/components/CAModal/CAModal.js
- Bug fix
Fixes issue where orderers & peers are not restarting after clicking `Update associated nodes` after a TLS cert was updated on a CA.
> send restart for each comp that has a new tls cert

- packages/apollo/src/components/ChannelModal/ChannelModal.js
- Bug fix
Adds the orderer org signature setep (when its needed) during the channel update wizard.
> add orderer org signature step on channel edit

- README.md
- packages/apollo/.secrets.baseline
- packages/athena/.secrets.baseline
- packages/stitch/.secrets.baseline
Add link to the recent meetup presentation on managing orderers without system channel
> add link to meetup - remove system channel

- packages/apollo/.secrets.baseline
- packages/apollo/package.json
- packages/apollo/src/App.js
- packages/apollo/src/components/CertificateAuthority/CertificateAuthority.js
- packages/apollo/src/components/ChaincodeModal/ChaincodeModal.js
- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/GenerateMSPModal/GenerateMSPModal.js
- packages/apollo/src/components/InstallChaincodeModal/InstallChaincodeModal.js
- packages/apollo/src/components/JoinChannelModal/JoinChannelModal.js
- packages/apollo/src/components/Orderers/Orderers.js
- packages/apollo/src/components/Peers/Peers.js
- packages/apollo/src/utils/medallia.js
- packages/athena/.secrets.baseline
- packages/stitch/.secrets.baseline
Signed-off-by: Nikhil Modem [nikhil.modem@ibm.com](mailto:nikhil.modem@ibm.com)
- Bug fix
- Removed Segment code
- Removed triggerSurvey code and references to it in other files
- Modified the `dev:apollo` command to work with the new `esbuild` change. This also fixes the `lerna run dev:apollo` command
> Prevent survey popup

- packages/apollo/src/components/Main/Main.js
- packages/athena/app.js
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/libs/migration_lib.js
- packages/athena/libs/settings.js
- packages/athena/routes/db_backups_apis.js
- packages/athena/routes/migration_apis.js
- packages/stitch/src/libs/proto_handlers/block_pb_lib.ts
- New feature
This is part of a wider unreleased feature to migrate console from one console to another. These apis are complete, but are not usable until the migration component is done.
- added api to get  overall migration status
- added api to migrate databases to new console
> add migration apis for status and db migration

- packages/apollo/.secrets.baseline
- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
- packages/athena/.secrets.baseline
- packages/stitch/.secrets.baseline
Signed-off-by: selvaprakash92 <selvaprakash92@gmail.com>
- Bug fix
orderer deletion label and package version update
> orderer deletion label and package version update

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/PageHeader/PageHeader.js
Signed-off-by: selvaprakash92 <selvaprakash92@gmail.com>
- New feature
To Notify the completion of Migration and Further steps
> Migration Completion Banner

- packages/apollo/src/app.scss
- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/Main/Main.js
- packages/apollo/src/components/MigrationPage/MigrationPage.js
- packages/apollo/src/components/MigrationPage/_migrationPage.scss
- packages/apollo/src/components/PageHeader/PageHeader.js
- New feature
More work towards the migration feature. This is the initial content for the migration page.
> started outline of the migration page

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/MigrationPage/MigrationPage.js
- packages/apollo/src/components/MigrationPage/_migrationPage.scss
- packages/apollo/src/components/PageHeader/PageHeader.js
Signed-off-by: Nikhil Modem <Nikhil.Modem@ibm.com>
- New feature
- More work on the migration page for migration feature
- Links the api with the frontend and present component migration status'
> Linked up the frontend with the migration api

- docker/console/Dockerfile
- packages/stitch/package-lock.json
- packages/stitch/package.json
Remove dev deps in image from athena and stitch installations.
> clean up dev deps in image

- packages/stitch/package-lock.json
- packages/stitch/package.json
- Bug fix
`ts-loader` needs to be a peer dependency. moved from dev dependency.
> move ts-loader to peer dep from dev dep

- packages/stitch/package-lock.json
- packages/stitch/package.json
- Bug fix
move typescript from dev dependency to a peer dependency.
> move typescript from dev dep to peer dep

- packages/stitch/package-lock.json
- Dependency updates
Fix NPM audit in stitch.
> fix-npm audit

- packages/apollo/src/components/ReleaseNotes/ReleaseNotes.js
- packages/apollo/src/components/WelcomeBanner/WelcomeBannerTile.js
- packages/apollo/src/components/WelcomeBanner/_welcomeBannerTile.scss
Signed-off-by: selvaprakash92 <selvaprakash92@gmail.com>
- Bug fix
Welcome page launch icon added
> Welcome page launch icon added

- packages/apollo/package-lock.json
- packages/apollo/src/utils/localization.js
- packages/stitch/package-lock.json
- Bug fix
In some cases unknown translation ids were breaking the page, preventing it from rendering.
> Localization fix

- packages/apollo/src/components/Mustgather/Mustgather.js
- Bug fix
The "mustgather" buttons should render if enabled.
> fix rendering of must gather buttons

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/CADetails/CADetails.js
- packages/apollo/src/components/Main/Main.js
- packages/apollo/src/components/MigrationPage/MigrationPage.js
- packages/athena/app.js
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/libs/couchdb.js
- packages/athena/libs/db_backup.js
- packages/athena/libs/jupiter_lib.js
- packages/athena/libs/lochness.js
- packages/athena/libs/middleware/middleware.js
- packages/athena/libs/migration_lib.js
- packages/athena/libs/misc.js
- packages/athena/libs/proxy_lib.js
- packages/athena/libs/settings.js
- packages/athena/libs/webhook_lib.js
- packages/athena/routes/db_backups_apis.js
- packages/athena/routes/migration_apis.js
- New feature
More migration code. Includes calling the jupiter apis and creating the initial login credentials.
> hook up migration apis to jupiter endpoints

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/MigrationPage/MigrationPage.js
- packages/apollo/src/components/MigrationPage/_migrationPage.scss
- packages/athena/libs/permissions_lib.js
- Bug fix
Fixes console crash when retrieving a valid iam token & tweaks the version error panel css.
> fix iam token crash and migration version panel

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/MigrationPage/MigrationPage.js
- packages/apollo/src/components/MigrationPage/_migrationPage.scss
- packages/apollo/src/components/ReleaseNotes/ReleaseNotes.js
- packages/apollo/src/components/WelcomeBanner/WelcomeBannerTile.js
- packages/apollo/src/utils/medallia.js
- packages/athena/libs/jupiter_lib.js
- packages/athena/libs/migration_lib.js
- packages/athena/libs/misc.js
- packages/athena/libs/other_apis_lib.js
- packages/athena/test/test-suites/lib/misc.test.js
- Bug fix
fix the lock error handling during migration. and pass jupiter errors to ui if possible.
> fix migration lock error handling

- packages/athena/libs/db_backup.js
- packages/athena/libs/migration_lib.js
- Bug fix
The json validation file shouldn't be in a backup, too big.
> remove json vaildation files from backups

- packages/athena/libs/migration_lib.js
- Bug fix
Fixes bugs when migrating the settings doc.
> fix errors when migrating a settings doc

- common/deploy_scripts/test_run_athena.sh
- docker/docker-compose-console.yaml
- packages/athena/README.md
- packages/athena/docs/db_backup_apis.md
- packages/athena/docs/other_apis.md
- packages/athena/env/README.md
- packages/athena/env/dev.json
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/public/releaseNotes.json
- packages/athena/test/test-suites/common-test-framework.js
Changing the default database names for migration.
> change default db name to use dashes

- common/deploy_scripts/test_run_athena.sh
- docker/docker-compose-console.yaml
- packages/athena/README.md
- packages/athena/docs/db_backup_apis.md
- packages/athena/docs/other_apis.md
- packages/athena/env/README.md
- packages/athena/env/dev.json
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/public/releaseNotes.json
- Bug fix
apparently there's an `s` on the system db name. `athena-systems`
> apparently there's an s on the system db

- common/deploy_scripts/test_run_athena.sh
- docker/docker-compose-console.yaml
- packages/athena/README.md
- packages/athena/docs/db_backup_apis.md
- packages/athena/docs/other_apis.md
- packages/athena/env/README.md
- packages/athena/env/dev.json
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/libs/migration_lib.js
- packages/athena/libs/settings.js
- packages/athena/scripts/create_databases.js
- Bug fix
Fix how we handle custom db names.
> fix custom db name handling

- packages/apollo/src/components/ExportModal/ExportModal.js
- packages/athena/libs/migration_lib.js
- Bug fix
The MSP docs and the signature collection docs need to be edited prior to migration.
> edit component docs prior to migration

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/MigrationPage/MigrationPage.js
- packages/athena/libs/deployer_lib.js
- packages/athena/public/releaseNotes.json
This PR allows selecting the "bad" fabric images. Which were all v2.2.9s, and v2.2.8-3.
> remove code blocking "bad" fabric images

- packages/apollo/src/components/MigrationPage/MigrationPage.js
- packages/athena/libs/iam_lib.js
- packages/athena/routes/permission_apis.js
- Bug fix
Fixes the IAM permission error on the `/iam/info` api.
> fix permission error related to /iam/info api

- packages/athena/libs/component_lib.js
- packages/athena/libs/migration_lib.js
- Bug fix
Migrated components need the migrated flag added, else it doesn't use the right url.
> fix urls of migrated components by adding migrated flag

- packages/athena/libs/comp_formatting_lib.js
- packages/athena/libs/migration_lib.js
- packages/athena/public/releaseNotes.json
- packages/stitch/src/libs/proto_handlers/proposal_response_pb_lib.ts
- Bug fix
Fixes setting the legacy field  `backend_addr` in component docs.
> build the legacy field backend_addr last

- packages/athena/app.js
- packages/athena/libs/deployer_lib.js
- packages/athena/libs/migration_lib.js
- packages/athena/libs/settings.js
- Bug fix
use the new deployer api to set infrastructure setting.
> use deployer api to set infrastructure setting

- packages/athena/libs/deployer_lib.js
- packages/athena/public/releaseNotes.json
> bump release notes

- packages/fabric-deployer/deployer/components/ca/get.go
- packages/fabric-deployer/deployer/components/orderer/get.go
- packages/fabric-deployer/deployer/components/peer/get.go
- packages/fabric-deployer/deployer/deployer.go
- Bug fix
Fixes building the endpoints for k8s clusters.
> fixes the migrated endpoints for k8s clusters only

- packages/athena/libs/deployer_lib.js
- packages/athena/libs/permissions_lib.js
- packages/athena/public/releaseNotes.json
- Bug fix
The test password strength api should work on saas consoles in prod.
> Allow saas consoles to test password strength

- packages/athena/libs/migration_lib.js
- packages/athena/public/releaseNotes.json
- packages/stitch/package-lock.json
- packages/stitch/package.json
- Bug fix
Set `mustgather_enabled` feature flag setting as `true` on migrated consoles.
> enable must gather on migrated consoles

- packages/athena/public/releaseNotes.json
- packages/stitch/package-lock.json
- packages/stitch/package.json
- Bug fix
Changes eslint in package.json to version that does not error during the webpack build.
> revert npm dep update of eslint to fix stitch build

- packages/athena/app.js
- packages/athena/libs/middleware/middleware.js
- packages/athena/libs/migration_lib.js
- packages/athena/public/releaseNotes.json
- Bug fix
Prevent migration status checking/monitoring from spinner in place forever.
> Prevent migration spin

- packages/athena/json_docs/default_settings_doc.json
> pen test CSP Header updation

- packages/athena/docs/_event_tracking_notes.md
- packages/athena/docs/logging_apis.md
- packages/athena/env/README.md
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/json_docs/json_validation/ibp_openapi_v2.yaml
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/libs/activity_tracker.js
- packages/athena/libs/event_tracker.js
- packages/athena/libs/migration_lib.js
- packages/athena/libs/other_apis_lib.js
- packages/athena/test/docs/other_apis_objects.json
- packages/athena/test/test-suites/common-test-framework.js
Update the doc on activity tracker and allow it to be turned on* via the setting.
> update activity tracker doc

- packages/athena/json_docs/default_settings_doc.json
- packages/athena/libs/permissions_lib.js
Pen test Input Validation update
> Pen test Input Validation update

- packages/athena/app.js
- during startup the console will now wait up to 90 seconds (was 60) for the database
- adds connection error to log if the console cannot connect to couchdb during startup
- also conforms the log messages
> add debug log for couch db connection errors

- docker/console/Dockerfile
- packages/athena/.gitignore
- packages/athena/_backups/README.md
- Bug fix
Node user needs write permissions to the `_backups` folder
> fix file permissons on the _backups folder

- packages/athena/libs/authentication_lib.js
- packages/athena/libs/permissions_lib.js
- packages/athena/public/releaseNotes.json
The login session will now be destroyed after changing a user password.
> destroy session on change password

- packages/athena/libs/deployer_lib.js
- Bug fix
Better parsing on the cluster type api to handle double quotes around the cluster type value. So this converts ` "\"k8s\""` to simply `"k8s"`
> conform "\"k8s\"" to "k8s" in cluster type api

- packages/athena/libs/migration_lib.js
- Bug fix
Add migration field to components on the original console.
> add migration field on existing components

- packages/athena/libs/migration_lib.js
- Bug fix
During migration the  component documents need to be decompressed so we can actually edit the docs. New fields get added.
> decompress component docs during migration to edit

- packages/apollo/src/components/OrdererModal/OrdererModal.js
- Bug fix
Fixes the associate identity with orderer modal bug introduced in build -40. The identity drop down was not loading.
> fix associate orderer modal regression

- packages/apollo/src/components/AddUserModal/AddUserModal.js
- packages/apollo/src/components/CAModal/CAModal.js
- packages/apollo/src/components/GenerateMSPModal/GenerateMSPModal.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/components/PeerModal/PeerModal.js
- Lint fix
Just some react warnings I noticed.
> fix react warnings

- packages/apollo/src/components/ChannelMembers/ChannelMembers.js
- packages/apollo/src/components/ItemContainerTile/ItemTileLabels/ItemTileLabels.js
- packages/apollo/src/components/Msps/Msps.js
- packages/apollo/src/components/OrdererAdmins/OrdererAdmins.js
- packages/apollo/src/components/OrdererMembers/OrdererMembers.js
- packages/apollo/src/utils/helper.js
- Bug fix
The node ou parsing was not consistent. Sometimes the code expected a string, other times boolean. Added a helper function to conform and handle both cases.
> fix node ou parsing

- packages/athena/routes/proxy_apis.js
Security improvement, by not accepting all http methods these "proxy" routes will no longer reply with CORS '*'.
> change proxy route cor settings

- docker/build_image.sh
- Bug fix
Change command to get tag from git, to add to docker image.
> fix docker tag

- packages/apollo/test/functional/features/9-Mustgather.feature
- packages/apollo/test/functional/steps/login.steps.js
- packages/apollo/test/functional/steps/navigation.steps.js
- Test update
mustgather tool case and xpath method update
> mustgather tool case 

- packages/apollo/src/components/OrdererConsenterModal/OrdererConsenterModal.js
- packages/apollo/src/components/OrdererDetails/ChannelParticipationUnjoinModal.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/rest/OrdererRestApi.js
- Bug fix
Fixed the id error on the orderer details page.
> fixes orderer details panel not loading b/c bad id

- .github/workflows/common.yml
- packages/apollo/.secrets.baseline
- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/NodeRestApi.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/apollo/src/utils/helper.js
- packages/athena/.secrets.baseline
- packages/stitch/.secrets.baseline
- Bug fix
- Fixes a few of the action buttons in the Orderer modal not rendering, preventing things like updating capabilities, and toggling maintenance mode.
- also we will now always show the `Open Channel Config` link in an orderer drill down. there's no longer a need to type out the `/debug/` route to activate this tool/link.
> fix a few action buttons not rendering in modal + removed need for debug route

- packages/apollo/src/App.js
- packages/apollo/src/components/ImportMspModal/ImportMspModal.js
- packages/apollo/src/components/Main/Main.js
- packages/apollo/src/components/MspDeleteModal/MspDeleteModal.js
- packages/apollo/src/components/OrdererAdmins/OrdererAdmins.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/OrdererMembers/OrdererMembers.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/apollo/test/unit/tests/MspDeleteModal.test.jsx
- packages/athena/public/releaseNotes.json
- Bug fix
This fixes adding and removing consortium members to the system channel of an ordering service.
> fix adding and removing of consortium members

- packages/apollo/src/components/Channels/Channels.js
- Bug fix
Fixes the toggle pending channel tile button.
> fixes the toggle pending channel tiles button

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/InstallChaincodeModal/InstallChaincodeModal.js
VSCode link removal from install chaincode
> VSCode link removal from install chaincode

- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/apollo/src/rest/StitchApi.js
- Bug fix
- fixed an error when adding a new orderer to an existing ordering service
- adding a lot more debug logs around the appending orderer flow
- fix error handling around the appending orderer flow, the code will now stop on the first "fatal" error, instead of continuing and showing the last (meaningless) error
> fix error when appending new orderer

- packages/apollo/src/components/EditAuthSchemePanel/EditAuthSchemePanel.js
- packages/apollo/src/components/Form/Form.js
- packages/apollo/src/components/ItemContainer/ItemContainer.js
- packages/apollo/src/components/ReallocateModal/ReallocateModal.js
- Bug fix
- fixes dropdown menus not showing the selected value
- fixes mutli select table errors which were creating a blank page
> Fix input option bug and table bug

- packages/apollo/src/components/Form/Form.js
- packages/athena/libs/authentication_lib.js
- Bug fix
- fixes the bug where it doesn't render the selected option in a fabric component dropdown input
> fix component dropdown option bug

- packages/athena/libs/other_apis_lib.js
- packages/athena/public/releaseNotes.json
- Bug fix
- need to update passport strategies when the auth scheme is changed
> update passport strats for oauth on a auth change

- packages/apollo/src/components/SidePanel/_sidePanel.scss
- packages/athena/public/releaseNotes.json
- Bug fix
Fixes the width of the button container to match the side panel
> Fix button size

- packages/athena/libs/deployer_lib.js
- Bug fix
- fixes the component data sync with deployer, now waits for the deployer changes to write to the db before rebuilding the url safelist
> fix the deployer sync timing

- packages/apollo/src/App.js
- packages/apollo/src/components/Login/Login.js
- packages/apollo/test/unit/tests/Login.test.jsx
- Bug fix
- changes the logout/login links from a url + path, to just an absolute path. more robust this way
> use absolute paths for logout/login links

- packages/athena/docs/_oauth.md
- packages/athena/docs/_permissions.md
Added content to the oauth readme
> add oauth doc content

- packages/athena/docs/_oauth.md
- packages/athena/docs/_permissions.md
> edited oauth docs

- packages/apollo/src/assets/i18n/en/messages.json
- Update api key doc link on the migration info page
> update api doc link

- packages/apollo/src/components/Form/Form.js
- packages/apollo/src/components/InstantiateChaincodeModal/InstantiateChaincodeModal.js
- packages/apollo/src/components/Wizard/Wizard.js
- packages/apollo/src/components/Wizard/_wizard.scss
- packages/athena/public/releaseNotes.json
- Bug fix
- fixes the blank screen bug when clicking the instantiate fabric 1.4 chaincode (overflow) button
> Fixes instantiate chaincode - blank screen

- packages/apollo/src/components/Form/Form.js
- packages/athena/public/releaseNotes.json
- Bug fix
- fixes the channel selection drop down box during the instantiate chaincode menu
> fix the channel dropdown select box for chaincode

- packages/apollo/src/rest/PeerRestApi.js
retry for smart contract error
> retry for smart contract error

- packages/athena/libs/component_lib.js
- packages/athena/public/releaseNotes.json
- Bug fix
fix status icon on components that do not have the legacy url route
> Fix component status

- packages/apollo/test/functional/steps/login.steps.js
- Test update
Updated login text to work with both IBP and HFL Support console
> Updated login text to work with both IBP and HFL Support console

- packages/apollo/src/assets/i18n/en/messages.json
- packages/stitch/src/libs/proto_handlers/collection_pb_lib.ts
- Bug fix
Added missing parameter checks to copy sdk's field to fabric's for private data collection fields
> Added checks for few private data collection parameters

- packages/apollo/src/app.scss
- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/AuditLogs/AuditLogs.js
- packages/apollo/src/components/AuditLogs/_auditLogs.scss
- packages/apollo/src/components/LeftNav/LeftNav.js
- packages/apollo/src/components/Main/Main.js
- packages/athena/.nsprc
- New feature
- 
inits a blank component, left nav button, route and a placeholder page for audit logging
> add blank page and route for audit logs

- packages/athena/public/releaseNotes.json
> bump release note

- dictionary_blockchain.txt
- packages/athena/json_docs/default_settings_doc.json
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/test/openapi/init_examples.js
- packages/athena/test/openapi/same_same.js
- packages/athena/test/openapi/unused.js
Removed csp header sources that we no longer use.
> edit csp headers to remove medallia sources

- packages/athena/public/releaseNotes.json
> added release notes on missing tags

- packages/apollo/package-lock.json
- packages/apollo/src/rest/IdentityApi.js
- packages/athena/libs/component_lib.js
- packages/athena/libs/config_blocks_lib.js
- packages/athena/libs/deployer_lib.js
- packages/athena/libs/middleware/middleware.js
- packages/athena/libs/misc.js
- packages/athena/libs/other_apis_lib.js
- packages/athena/libs/permissions_lib.js
- packages/athena/libs/signature_collection_lib.js
- packages/athena/public/releaseNotes.json
- packages/athena/routes/permission_apis.js
- packages/athena/test/test-suites/lib/misc.test.js
- packages/athena/test/test-suites/routes/permission_apis.test.js
- Bug fix
many bug fixes/improvements on the audit log panel
> tidy up audit log messages/events

- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
> showing settings button on channel details

- packages/apollo/src/rest/EventsRestApi.js
- packages/athena/libs/component_lib.js
- packages/athena/libs/other_apis_lib.js
- packages/athena/libs/patch_lib.js
- packages/athena/public/releaseNotes.json
- packages/athena/routes/component_apis.js
- Bug fix
The version summary report was not getting the versions of CAs.
> Fix ca version gather

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/StickySection/StickySection.js
- packages/apollo/src/utils/actionsHelper.js
- Bug fix
- writers should be able to delete **imported** components
> allow writers to delete imported

- packages/apollo/test/cypress/e2e/features/10-UserManagement.feature
- packages/apollo/test/cypress/e2e/features/11-Misc Cases.feature
- packages/apollo/test/cypress/e2e/features/12-AuditLog.feature
- packages/apollo/test/cypress/support/index.js
- packages/apollo/test/cypress/support/step_definitions/navigation_steps.js
- packages/apollo/test/cypress/support/step_definitions/notifcation_steps.js
- Test update
updated audit log entry
> updated audit log entry

- packages/apollo/test/cypress/cypress.config.ts
- packages/apollo/test/cypress/e2e/features/12-AuditLog.feature
- packages/apollo/test/cypress/support/index.js
- packages/apollo/test/cypress/support/step_definitions/login_steps.js
- packages/apollo/test/cypress/support/step_definitions/navigation_steps.js
- Test update
Added reload step to avoid timeout errors in pipeline execution
> Added reload step to avoid timeout errors in pipeline execution

- packages/apollo/test/cypress/e2e/features/11-Misc Cases.feature
- Test update
added scenario to verify version summary button
> added scenario to verify version summary button

- packages/fabric-deployer/config/config.go
- packages/fabric-deployer/config/config_struct.go
- packages/fabric-deployer/config/config_test.go
- packages/fabric-deployer/deployer/components/peer/get.go
- packages/fabric-deployer/deployer/components/peer/get_test.go
- packages/fabric-deployer/deployer/components/peer/patch_test.go
- packages/fabric-deployer/deployer/components/peer/peer.go
- packages/fabric-deployer/deployer/components/peer/peer_test.go
- packages/fabric-deployer/deployer/components/peer/update_test.go
- packages/fabric-deployer/docs/v3_apis.md
- packages/fabric-deployer/docs/v3_responses/versions_all.json
- packages/fabric-deployer/docs/v3_responses/versions_peer.json
- packages/fabric-deployer/sampleconfigs/local-config.yaml
> Removing FluentD references

- packages/fabric-deployer/Dockerfile
- packages/fabric-deployer/Makefile
- packages/fabric-deployer/deployer/components/operator/get_test.go
- packages/fabric-deployer/deployer/components/operator/operator.go
- packages/fabric-deployer/deployer/components/operator/operator_test.go
- packages/fabric-deployer/deployer/deployer.go
- Bug fix
To make hsm flow work again by adding the missing apis
> Add hsmconfig APIs for hsm to wrok

- packages/athena/.nsprc
- packages/athena/app.js
- packages/athena/libs/misc.js
- packages/athena/libs/request_axios.js
- packages/athena/package-lock.json
- packages/athena/package.json
- packages/athena/scripts/stress_couchdb.js
- packages/athena/test/axios.js
- packages/athena/test/test-suites/common-test-framework.js
- packages/athena/test/test-suites/lib/couchdb.test.js
- Bug fix
Replaces the `request` module, which is what we use for all http requests, with `axios`. (because request is no longer being maintained)
> replace request module with axios via wrapper

- packages/apollo/src/components/ChaincodeModal/ChaincodeModal.js
- packages/apollo/src/components/ChannelChaincode/ChannelChaincode.js
> disable update button for package

- packages/apollo/test/cypress/e2e/features/12-AuditLog.feature
- packages/apollo/test/cypress/e2e/features/13-ConsoleAPI.feature
- packages/apollo/test/cypress/support/step_definitions/input_steps.js
- packages/apollo/test/cypress/support/step_definitions/notifcation_steps.js
- Test update
API key test cases from console
> API key test cases from console

- packages/athena/public/releaseNotes.json
> update releaes notes

- packages/apollo/src/components/ImportCAModal/ImportCAModal.js
- Bug fix
The last build was incorrectly showing steps during the deploy CA flow that were not selected.
> fixes deploy ca flow, hides unselected steps

- packages/fabric-deployer/go.mod
- packages/fabric-deployer/go.sum
As per CVE-2023-28842 and many others.
> Upgrade deployer to latest Docker Golang client.

- .gitignore
- .vscode/settings.json
- packages/athena/env/README.md
- Other
adds VScode setting to always add git "sign off" line to commit message
> add vs code option to always add "sign off"

- packages/apollo/src/components/Support/Support.js
> hide mustgather section for readers and writers

- packages/apollo/test/cypress/cypress.config.ts
- packages/apollo/test/cypress/e2e/features/05-Install20SmartContract.feature
- packages/apollo/test/cypress/e2e/features/11-Misc Cases.feature
- packages/apollo/test/cypress/e2e/features/13-ConsoleAPI.feature
- packages/apollo/test/cypress/support/step_definitions/channel_steps.js
- packages/apollo/test/cypress/support/step_definitions/navigation_steps.js
- Test update
Changes as per timeout error in pipeline
> Changes as per timeout error in pipeline

- packages/athena/libs/db_backup.js
- packages/athena/libs/validation_lib.js
- Bug fix
- Code Improvement
- Sanitise input payload of db backup api
- Improve code by duplicate conditions
> sanitise payload of db backup api

- packages/apollo/src/App.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/rest/CertificateAuthorityRestApi.js
- packages/apollo/src/rest/LoginApi.js
- packages/apollo/src/rest/NodeRestApi.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/apollo/src/rest/SettingsApi.js
- packages/apollo/src/rest/SignatureRestApi.js
- packages/apollo/src/rest/UserSettingsRestApi.js
- packages/apollo/src/utils/status.js
- packages/apollo/test/cypress/e2e/features/12-AuditLog.feature
- packages/athena/docs/_v1_to_v2_changes.md
- packages/athena/docs/deployer_apis.md
- packages/athena/docs/logging_apis.md
- packages/athena/docs/other_apis.md
- packages/athena/json_docs/OpTools.master.postman_collection.json
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/libs/activity_tracker.js
- packages/athena/libs/lockout.js
- packages/athena/libs/logging_apis_lib.js
- packages/athena/libs/ot_misc.js
- packages/athena/libs/settings.js
- packages/athena/routes/deployer_apis.js
- packages/athena/routes/legacy/deployer_apis_v1.js
- packages/athena/test/test-suites/common-test-framework.js
- packages/athena/test/test-suites/lib/middleware.test.js
- packages/athena/test/test-suites/lib/ot_misc.test.js
- packages/athena/test/test-suites/lib/validation_lib.test.js
- packages/athena/test/test-suites/routes/deployer_apis.test.js
- packages/athena/test/test-suites/routes/logging_apis.test.js
- Clean up
- Removing `/saas/` from api routes (legacy text), this only effects internal routes the webapp uses
- some internal routes still used `/v2/`, changed to use `/v3/`
> remove "saas" and replace "v2" text from  api paths

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- Bug fix
Issue fix channel creation fail on join orderer
> join orderer issue fix on without system channel

- packages/apollo/src/components/SignatureDetailModal/SignatureDetailModal.js
- Bug fix
- Added audit log if any configuration changes made in existing channel
> added audit log on channel update, add or delete any configuration

- packages/apollo/src/components/Channels/Channels.js
- Bug fix
- Handle error while switching channel UI from Grid to List view.
> Fix for Channel UI change from Grid to List view

- packages/athena/app.js
- packages/athena/libs/settings.js
- packages/athena/libs/validation_lib.js
- packages/athena/scripts/create_databases.js
- Improvement (Performance improvement etc)
- Performance improvement update and log added
> log added on application startup tasks

- packages/apollo/src/components/Channels/Channels.js
- Bug fix
- Show created channel in channels if user close window after channel creation.
> Show channel under pending channel if user close window after creation

- dictionary_blockchain.txt
- packages/athena/docs/permission_apis.md
- packages/athena/json_docs/json_validation/ibp_openapi_v3.yaml
- packages/athena/libs/permissions_lib.js
- packages/athena/routes/permission_apis.js
- Bug fix
- fixes bearer token generation when auth is an api key
- uses swagger file for validation of the create-access-token api
> fix access token generation if using api key

- packages/athena/public/releaseNotes.json
> add release note

- packages/apollo/src/components/JoinChannelModal/JoinChannelModal.js
- Bug fix
- reverting join channel changes from https://github.com/hyperledger-labs/fabric-operations-console/pull/638
> revert channel channel changes from 638

- packages/apollo/src/components/ChaincodeModal/ChaincodeModal.js
- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/NodeRestApi.js
- packages/apollo/src/rest/StitchApi.js
- Bug fix
- it was not correctly building array of orderer urls to use on retries for chaincode related transactions
> fix builidng list of possible orderer nodes

- packages/apollo/src/components/SignatureDetailModal/SignatureDetailModal.js
- Bug fix
- there was a crash/error when submitting a channel creation tx when ordering capabilities were changed from the default
, this prevented creating channels that were of this nature
> safer nested data navigation in signature submission

- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/NodeRestApi.js
- packages/athena/public/releaseNotes.json
- Bug fix
- fixes an error in some circumstances when creating a chaincode definition approval
> fix chaincode definition approval error

- packages/athena/libs/settings.js
- removes legacy code around setting the internal flag `console_type`
> simplify console_type flag setting

- packages/apollo/src/App.js
- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/Support/Support.js
- Bug fix
- Update help doc links according to console type
> Update help doc links according to console type

- packages/apollo/package-lock.json
- packages/apollo/package.json
- packages/apollo/src/utils/helper.js
- Bug fix
- [CVE] decompress CVE vulnerability fix
> CVE fix for decompress because of Directory Traversal

- packages/apollo/src/components/Channels/Channels.js
- Bug fix
Fix issue channel visible after deletion on channel list
> fetch channels list with skip cache just after channel deletion

- packages/apollo/test/cypress/e2e/features/11-TestWriter.feature
- packages/apollo/test/cypress/e2e/features/12-TestReader.feature
- packages/apollo/test/cypress/support/step_definitions/navigation_steps.js
- Test update
Removed duplicate step definition and alignment in test case file
> removed duplicate step definition and alignment

- packages/athena/libs/settings.js
- Bug fix
- Fix console type in settings api, due to that point wrong support url
> fix for console type on settings api

- packages/athena/public/releaseNotes.json
> Releasenote20240322

- packages/apollo/src/assets/i18n/en/messages.json
- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- Bug fix
- Join existing channel by ordering service node without system channel, give warning if OS node msp does not part of channel
> os node add to existing channel fix

- .github/workflows/apollo.yml
- .github/workflows/athena.yml
- .github/workflows/common.yml
- .github/workflows/deploy.yml
- .github/workflows/grpc-web-docker.yml
- .github/workflows/stitch.yml
- docker/console/Dockerfile
- docker/grpc-web/Dockerfile
* Upgrade console image(s) to UBI-9 base image and build images.
* Upgrade grpcweb base image to Go v1.21.9.
* Upgrade to Python v3.12 in workflows.
My motivation is that many of these OSes and runtime versions have either gone End of Life or are approaching EOL, and many of them contain known security vulnerabilities.
> Upgrade underlying runtimes/os.

- packages/apollo/src/hoc/withLocalize.js
- Bug fix
- handle case for render html translated content
> handle case for render html translated content

- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
- Bug fix
- Fix issue for join ordering node to channel
> ordering node join channel issue fix

- packages/athena/public/releaseNotes.json
> bum release note

- packages/apollo/src/App.js
- packages/apollo/src/components/AddUserModal/AddUserModal.js
- packages/apollo/src/components/Login/Login.js
- packages/apollo/test/unit/tests/Login.test.jsx
- packages/athena/libs/permissions_lib.js
- packages/athena/test/test-suites/routes/permission_apis.test.js
- Bug fix
- Revert message to msg same as other apis
> keep msg key for 400 validation errors same as other apis

- packages/apollo/src/App.js
- packages/apollo/src/components/ChipInput.js
- packages/apollo/src/components/EmailChips/EmailChips.js
- packages/apollo/src/components/GenericChips/GenericChips.js
- Bug fix
UI issue fix for updated ChipInput
> ui fix and style update for chip library updates

- packages/apollo/src/components/ReleaseNotes/ReleaseNotes.js
- packages/apollo/src/components/Timeline/Timeline.js
- packages/apollo/src/components/TimelineCancelButton/TimelineCancelButton.js
- Bug fix
- Translation fix with updated library
> Fix for console setup open source issue

- packages/apollo/package-lock.json
- packages/apollo/package.json
- packages/apollo/src/components/Main/Main.js
- Improvement
Updated react-idle-timer library
> updated react-idle-timer library

- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/ChannelModal/Wizard/ACL/ACL.js
- packages/apollo/src/components/ChannelModal/Wizard/BlockCuttingParams/BlockCuttingParams.js
- packages/apollo/src/components/ChannelModal/Wizard/Capabilities/Capabilities.js
- packages/apollo/src/components/ChannelModal/Wizard/ChaincodePolicy/ChaincodePolicy.js
- packages/apollo/src/components/ChannelModal/Wizard/Consenters/Consenters.js
- packages/apollo/src/components/ChannelModal/Wizard/Details/Details.js
- packages/apollo/src/components/ChannelModal/Wizard/OSNJoin/OSNJoin.js
- packages/apollo/src/components/ChannelModal/Wizard/OrdererOrganizations/OrdererOrganizations.js
- packages/apollo/src/components/ChannelModal/Wizard/OrdererSignature/OrdererSignature.js
- packages/apollo/src/components/ChannelModal/Wizard/OrgSignature/OrgSignature.js
- packages/apollo/src/components/ChannelModal/Wizard/Policy/Policy.js
- packages/apollo/src/components/ChannelModal/Wizard/Prerequisites/Prerequisites.js
- packages/apollo/src/components/ChannelModal/Wizard/Review/Review.js
- packages/apollo/src/components/JoinOSNChannelModal/JoinOSNChannelModal.js
> translate issue fix

- packages/apollo/src/components/ChannelModal/Wizard/Admins/Admins.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- Bug fix
- Fic channel update issue screen getting blank
- UI issue fix while removing orderer
> channel update and remove orderer ui fix

- packages/apollo/src/components/Form/Form.js
- Bug fix
- Release doc update
- Translation issue fix signature approval screen
>  translation issue fix on sinature approval screen

- packages/athena/public/releaseNotes.json
- Bug fix
- Release doc update
- Translation issue fix signature approval screen
>  translation issue fix on signature approval screen

- packages/apollo/test/cypress/e2e/features/16-ConsoleAPIv3.feature
- packages/apollo/test/cypress/support/step_definitions/api_steps.js
- Bug fix
- New feature
- Test update
> Adding Console API tests

- packages/apollo/src/App.js
- packages/apollo/src/components/Access/Access.js
- packages/apollo/src/components/AddUserModal/AddUserModal.js
- packages/apollo/src/components/AuditLogs/AuditLogs.js
- packages/apollo/src/components/AuthDetails/AuthDetails.js
- packages/apollo/src/components/AuthSetupAddUsers/AuthSetupAddUsers.js
- packages/apollo/src/components/BlockchainPagination/BlockchainPagination.js
> Fix code linters

- packages/athena/routes/signature_collection_apis.js
> bump change log

- packages/athena/public/releaseNotes.json
- packages/athena/routes/signature_collection_apis.js
> release note and revert unwanted code

- packages/athena/public/releaseNotes.json
> release note added

- packages/apollo/src/components/GenerateMSPModal/GenerateMSPModal.js
- packages/apollo/test/cypress/fixtures/config.json
- Bug fix
- Fix Error: Maximum update depth exceeded
> max update limit exceed issue fix on msp creation

- packages/athena/json_docs/default_settings_doc.json
- Bug fix
Removed wild card directives
> removed wild card directives

- packages/athena/json_docs/default_settings_doc.json
- packages/athena/public/releaseNotes.json
- Bug fix
- Release doc update
> revert connect src and update release doc

- docker/console/Dockerfile
- Nodejs version update
- Nodejs version update from 18 to 20
> update node version from 18 to 20

- packages/apollo/eslint.config.mjs
- packages/apollo/src/components/CADetails/CADetails.js
- packages/apollo/src/components/Form/Form.js
- packages/apollo/src/components/JsonInput/JsonInput.js
- packages/apollo/src/components/MspDetailsModal/MspDetailsModal.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/RenderHTML/RenderHTML.jsx
- packages/apollo/src/components/RenderHTML/RenderParamHTML.jsx
- packages/apollo/src/components/SignatureDetailModal/SignatureDetailModal.js
- packages/apollo/src/hoc/withRouter.jsx
- packages/athena/public/releaseNotes.json
- Bug fix
- Update available screen issue fix on CA and Orderer Detail screen
- Fix issue while reloading ordering node screen
> ca and orderer detail patch available ui fix and ordering node screen load issue fix

- packages/apollo/src/assets/i18n/en/messages.json
Earlier link was not valid anymore, so updated the document link for release notes option
> updated doc link for release notes

- packages/apollo/src/components/Form/Form.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/athena/public/releaseNotes.json
> automation test case issue debug point and issue fix

- packages/apollo/src/components/Form/Form.js
- packages/apollo/src/components/OrdererDetails/OrdererDetails.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/components/TitleBar/TitleBar.js
- packages/apollo/src/redux/LocalizeWrapper.js
- Bug fix
- Dropdown change issue and ordering node issue fix
> Dropdown change issue and ordering node issue fix

- packages/apollo/eslint.config.mjs
- packages/apollo/src/components/Access/Access.js
- packages/apollo/src/components/CADetails/CADetails.js
- packages/apollo/src/components/ChannelDetails/ChannelDetails.js
- packages/apollo/src/components/ChannelModal/Wizard/OrdererOrganizations/OrdererOrganizations.js
- packages/apollo/src/components/ChipInput.js
- packages/apollo/src/components/GenerateMSPModal/GenerateMSPModal.js
- packages/apollo/src/components/ImportCAModal/ImportCAModal.js
- packages/apollo/src/components/ImportOrdererModal/ImportOrdererModal.js
- packages/apollo/src/components/ImportPeerModal/ImportPeerModal.js
- packages/apollo/src/components/Login/Login.js
- packages/apollo/src/components/PageContainer/PageContainer.js
- packages/apollo/src/components/PeerDetails/PeerDetails.js
- packages/apollo/src/components/ProposeChaincodeModal/ProposeChaincodeModal.js
- packages/apollo/src/components/SidePanel/__mocks__/SidePanel.js
- packages/apollo/src/components/SidePanelInlineConfirmation/SidePanelInlineConfirmation.js
- packages/apollo/src/components/SignatureDetailModal/SignatureDetailModal.js
- packages/apollo/src/components/Timeline/Timeline.js
- packages/apollo/src/hoc/withRouter.jsx
- packages/apollo/src/registerServiceWorker.js
- packages/apollo/src/rest/PeerRestApi.js
- packages/apollo/src/utils/helper.js
- packages/athena/public/releaseNotes.json
> update lint rule

- packages/apollo/src/components/Form/Form.js
- packages/athena/public/releaseNotes.json
> Issue dropdown

- packages/athena/public/releaseNotes.json
> bump up release notes

- packages/fabric-deployer/Makefile
- packages/fabric-deployer/go.mod
- packages/fabric-deployer/go.sum
> moving to GO 1.23.1

- packages/athena/public/releaseNotes.json
Update releaseNotes.json 1.0.9-26
> Update releaseNotes for 1.0.9-26

- .github/workflows/deploy.yml
Added permission field due to error in building console image
> Update deploy.yml workflow

- .github/workflows/apollo.yml
- .github/workflows/athena.yml
- .github/workflows/common.yml
- .github/workflows/stitch.yml
- Bug fix
- New feature
- Test update
> Enable 'experimental' branch builds

- packages/athena/package-lock.json
- packages/athena/package.json
- packages/stitch/package-lock.json
updated package npm audit fix - CVE-204-47764
> updated package - CVE-204-47764

- packages/apollo/package-lock.json
- packages/apollo/package.json
- packages/athena/package-lock.json
Package update:
- http-proxy-middleware - in packages/apollo
- elliptic - in packages/Athena
> updated packages http-proxy-middleware and elliptic

- packages/athena/package-lock.json
> updated elliptic version

- packages/athena/public/releaseNotes.json
> Bump up release note 1.0.9-29

- packages/apollo/test/cypress/e2e/features/02-BuildNetwork.feature
- packages/apollo/test/cypress/e2e/features/09-BuildANetwork_Without_SysChannel.feature
- Test update
updating test case to 2.5.x as 2.2.x is disabled
> updating test case to 2.5.x as 2.2.x is disabled

- packages/apollo/test/cypress/e2e/features/02-BuildNetwork.feature
- packages/apollo/test/cypress/e2e/features/03-JoinANetwork.feature
- Test update
Remove steps to select fabric version for peers
> Remove steps to select fabric version for peers

- packages/athena/package-lock.json
> Security Fix for PVR0572811

- packages/athena/public/releaseNotes.json
Update releaseNotes for 1.0.9-31
> Update release notes for 1.0.9-31

- packages/athena/public/releaseNotes.json
Update release notes for 1.0.9-32
> Update release notes for 1.0.9-32

- packages/apollo/package-lock.json
- packages/apollo/package.json
- packages/apollo/src/components/ChannelModal/ChannelModal.js
- packages/apollo/src/components/ChannelModal/Wizard/BlockCuttingParams/BlockCuttingParams.js
- packages/apollo/src/components/OrdererModal/OrdererModal.js
- packages/apollo/src/components/SignatureDetailModal/SignatureDetailModal.js
- packages/apollo/src/rest/ChannelApi.js
- packages/apollo/src/rest/OrdererRestApi.js
- packages/apollo/src/utils/parseDuration.js
- packages/athena/package-lock.json
- packages/athena/package.json
CVE-2024-57965 | updated axios to 1.7.9
elliptic to 6.6.1
Removed depedency of parse-duration by creating wrapper
> CVE-2024-57965 | updated axios to 1.7.9

- docker/grpc-web/Dockerfile
Bump grpc-web Dockerfile to Go 1.23.5
> Bump grpc-web Dockerfile to Go 1.23.5

- packages/athena/package-lock.json
- packages/athena/package.json
CVE-2025-27152 | updated axios to 1.8.2
> CVE-2025-27152 | updated axios to 1.8.2

- packages/apollo/src/utils/parseDuration.js
- Fix lint warnings from apollo github action
- Fix formatting
> Fix lint warnings in parseDuration.js

- packages/athena/public/releaseNotes.json
Updated release note for 1.0.9-35
> Updated release note for 1.0.9-35

- packages/apollo/test/cypress/package-lock.json
Update cypress dependencies using "npm audit fix".
> Bump @babel/runtime from 7.23.2 to 7.26.10 in cypress

- packages/athena/public/releaseNotes.json
Update releaseNotes.json - 1.0.9-36
> Update releaseNotes.json - 1.0.9-36

- docker/console/Dockerfile
- packages/athena/deploy_scripts/build_image_names.sh
- packages/fabric-deployer/Dockerfile
- scripts/replace_license_headers.js
Base image change into UBI8 to UBI9
> UBI9 Base Image Changes

- packages/athena/public/releaseNotes.json
Update releaseNotes.json 1.0.9-37
> Update releaseNotes.json 1.0.9-37

- docker/grpc-web/Dockerfile
Bump grpc-web Dockerfile to Go 1.24.3
> Bump grpc-web Dockerfile to Go 1.24.3

- .github/workflows/image-build.yaml
- .github/workflows/unit-tests.yaml
- packages/fabric-deployer/Makefile
- packages/fabric-deployer/go.mod
> Bump go to 1.24.3

- package-lock.json
- package.json
- packages/apollo/package-lock.json
- packages/apollo/package.json
- Dependencies update
Update tar to 6.2.1 and cross-spawn to 7.0.6
> update tar to 6.2.1 and cross-spawn to 7.0.6

- packages/apollo/package-lock.json
- Security patch
Update pbkdf2 to 3.1.3
> update pbkdf2 to 3.1.3

- packages/athena/public/releaseNotes.json
Update releaseNotes.json for 1.0.9-42
> Update releaseNotes.json for 1.0.9-42
